// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophermart/internal/models"
)

// AccountServiceMock implements mm_withdrawhandler.AccountService
type AccountServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcWithdraw          func(ctx context.Context, withdrawal models.Withdrawal) (err error)
	funcWithdrawOrigin    string
	inspectFuncWithdraw   func(ctx context.Context, withdrawal models.Withdrawal)
	afterWithdrawCounter  uint64
	beforeWithdrawCounter uint64
	WithdrawMock          mAccountServiceMockWithdraw
}

// NewAccountServiceMock returns a mock for mm_withdrawhandler.AccountService
func NewAccountServiceMock(t minimock.Tester) *AccountServiceMock {
	m := &AccountServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.WithdrawMock = mAccountServiceMockWithdraw{mock: m}
	m.WithdrawMock.callArgs = []*AccountServiceMockWithdrawParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAccountServiceMockWithdraw struct {
	optional           bool
	mock               *AccountServiceMock
	defaultExpectation *AccountServiceMockWithdrawExpectation
	expectations       []*AccountServiceMockWithdrawExpectation

	callArgs []*AccountServiceMockWithdrawParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccountServiceMockWithdrawExpectation specifies expectation struct of the AccountService.Withdraw
type AccountServiceMockWithdrawExpectation struct {
	mock               *AccountServiceMock
	params             *AccountServiceMockWithdrawParams
	paramPtrs          *AccountServiceMockWithdrawParamPtrs
	expectationOrigins AccountServiceMockWithdrawExpectationOrigins
	results            *AccountServiceMockWithdrawResults
	returnOrigin       string
	Counter            uint64
}

// AccountServiceMockWithdrawParams contains parameters of the AccountService.Withdraw
type AccountServiceMockWithdrawParams struct {
	ctx        context.Context
	withdrawal models.Withdrawal
}

// AccountServiceMockWithdrawParamPtrs contains pointers to parameters of the AccountService.Withdraw
type AccountServiceMockWithdrawParamPtrs struct {
	ctx        *context.Context
	withdrawal *models.Withdrawal
}

// AccountServiceMockWithdrawResults contains results of the AccountService.Withdraw
type AccountServiceMockWithdrawResults struct {
	err error
}

// AccountServiceMockWithdrawOrigins contains origins of expectations of the AccountService.Withdraw
type AccountServiceMockWithdrawExpectationOrigins struct {
	origin           string
	originCtx        string
	originWithdrawal string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmWithdraw *mAccountServiceMockWithdraw) Optional() *mAccountServiceMockWithdraw {
	mmWithdraw.optional = true
	return mmWithdraw
}

// Expect sets up expected params for AccountService.Withdraw
func (mmWithdraw *mAccountServiceMockWithdraw) Expect(ctx context.Context, withdrawal models.Withdrawal) *mAccountServiceMockWithdraw {
	if mmWithdraw.mock.funcWithdraw != nil {
		mmWithdraw.mock.t.Fatalf("AccountServiceMock.Withdraw mock is already set by Set")
	}

	if mmWithdraw.defaultExpectation == nil {
		mmWithdraw.defaultExpectation = &AccountServiceMockWithdrawExpectation{}
	}

	if mmWithdraw.defaultExpectation.paramPtrs != nil {
		mmWithdraw.mock.t.Fatalf("AccountServiceMock.Withdraw mock is already set by ExpectParams functions")
	}

	mmWithdraw.defaultExpectation.params = &AccountServiceMockWithdrawParams{ctx, withdrawal}
	mmWithdraw.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmWithdraw.expectations {
		if minimock.Equal(e.params, mmWithdraw.defaultExpectation.params) {
			mmWithdraw.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWithdraw.defaultExpectation.params)
		}
	}

	return mmWithdraw
}

// ExpectCtxParam1 sets up expected param ctx for AccountService.Withdraw
func (mmWithdraw *mAccountServiceMockWithdraw) ExpectCtxParam1(ctx context.Context) *mAccountServiceMockWithdraw {
	if mmWithdraw.mock.funcWithdraw != nil {
		mmWithdraw.mock.t.Fatalf("AccountServiceMock.Withdraw mock is already set by Set")
	}

	if mmWithdraw.defaultExpectation == nil {
		mmWithdraw.defaultExpectation = &AccountServiceMockWithdrawExpectation{}
	}

	if mmWithdraw.defaultExpectation.params != nil {
		mmWithdraw.mock.t.Fatalf("AccountServiceMock.Withdraw mock is already set by Expect")
	}

	if mmWithdraw.defaultExpectation.paramPtrs == nil {
		mmWithdraw.defaultExpectation.paramPtrs = &AccountServiceMockWithdrawParamPtrs{}
	}
	mmWithdraw.defaultExpectation.paramPtrs.ctx = &ctx
	mmWithdraw.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmWithdraw
}

// ExpectWithdrawalParam2 sets up expected param withdrawal for AccountService.Withdraw
func (mmWithdraw *mAccountServiceMockWithdraw) ExpectWithdrawalParam2(withdrawal models.Withdrawal) *mAccountServiceMockWithdraw {
	if mmWithdraw.mock.funcWithdraw != nil {
		mmWithdraw.mock.t.Fatalf("AccountServiceMock.Withdraw mock is already set by Set")
	}

	if mmWithdraw.defaultExpectation == nil {
		mmWithdraw.defaultExpectation = &AccountServiceMockWithdrawExpectation{}
	}

	if mmWithdraw.defaultExpectation.params != nil {
		mmWithdraw.mock.t.Fatalf("AccountServiceMock.Withdraw mock is already set by Expect")
	}

	if mmWithdraw.defaultExpectation.paramPtrs == nil {
		mmWithdraw.defaultExpectation.paramPtrs = &AccountServiceMockWithdrawParamPtrs{}
	}
	mmWithdraw.defaultExpectation.paramPtrs.withdrawal = &withdrawal
	mmWithdraw.defaultExpectation.expectationOrigins.originWithdrawal = minimock.CallerInfo(1)

	return mmWithdraw
}

// Inspect accepts an inspector function that has same arguments as the AccountService.Withdraw
func (mmWithdraw *mAccountServiceMockWithdraw) Inspect(f func(ctx context.Context, withdrawal models.Withdrawal)) *mAccountServiceMockWithdraw {
	if mmWithdraw.mock.inspectFuncWithdraw != nil {
		mmWithdraw.mock.t.Fatalf("Inspect function is already set for AccountServiceMock.Withdraw")
	}

	mmWithdraw.mock.inspectFuncWithdraw = f

	return mmWithdraw
}

// Return sets up results that will be returned by AccountService.Withdraw
func (mmWithdraw *mAccountServiceMockWithdraw) Return(err error) *AccountServiceMock {
	if mmWithdraw.mock.funcWithdraw != nil {
		mmWithdraw.mock.t.Fatalf("AccountServiceMock.Withdraw mock is already set by Set")
	}

	if mmWithdraw.defaultExpectation == nil {
		mmWithdraw.defaultExpectation = &AccountServiceMockWithdrawExpectation{mock: mmWithdraw.mock}
	}
	mmWithdraw.defaultExpectation.results = &AccountServiceMockWithdrawResults{err}
	mmWithdraw.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmWithdraw.mock
}

// Set uses given function f to mock the AccountService.Withdraw method
func (mmWithdraw *mAccountServiceMockWithdraw) Set(f func(ctx context.Context, withdrawal models.Withdrawal) (err error)) *AccountServiceMock {
	if mmWithdraw.defaultExpectation != nil {
		mmWithdraw.mock.t.Fatalf("Default expectation is already set for the AccountService.Withdraw method")
	}

	if len(mmWithdraw.expectations) > 0 {
		mmWithdraw.mock.t.Fatalf("Some expectations are already set for the AccountService.Withdraw method")
	}

	mmWithdraw.mock.funcWithdraw = f
	mmWithdraw.mock.funcWithdrawOrigin = minimock.CallerInfo(1)
	return mmWithdraw.mock
}

// When sets expectation for the AccountService.Withdraw which will trigger the result defined by the following
// Then helper
func (mmWithdraw *mAccountServiceMockWithdraw) When(ctx context.Context, withdrawal models.Withdrawal) *AccountServiceMockWithdrawExpectation {
	if mmWithdraw.mock.funcWithdraw != nil {
		mmWithdraw.mock.t.Fatalf("AccountServiceMock.Withdraw mock is already set by Set")
	}

	expectation := &AccountServiceMockWithdrawExpectation{
		mock:               mmWithdraw.mock,
		params:             &AccountServiceMockWithdrawParams{ctx, withdrawal},
		expectationOrigins: AccountServiceMockWithdrawExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmWithdraw.expectations = append(mmWithdraw.expectations, expectation)
	return expectation
}

// Then sets up AccountService.Withdraw return parameters for the expectation previously defined by the When method
func (e *AccountServiceMockWithdrawExpectation) Then(err error) *AccountServiceMock {
	e.results = &AccountServiceMockWithdrawResults{err}
	return e.mock
}

// Times sets number of times AccountService.Withdraw should be invoked
func (mmWithdraw *mAccountServiceMockWithdraw) Times(n uint64) *mAccountServiceMockWithdraw {
	if n == 0 {
		mmWithdraw.mock.t.Fatalf("Times of AccountServiceMock.Withdraw mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmWithdraw.expectedInvocations, n)
	mmWithdraw.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmWithdraw
}

func (mmWithdraw *mAccountServiceMockWithdraw) invocationsDone() bool {
	if len(mmWithdraw.expectations) == 0 && mmWithdraw.defaultExpectation == nil && mmWithdraw.mock.funcWithdraw == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmWithdraw.mock.afterWithdrawCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmWithdraw.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Withdraw implements mm_withdrawhandler.AccountService
func (mmWithdraw *AccountServiceMock) Withdraw(ctx context.Context, withdrawal models.Withdrawal) (err error) {
	mm_atomic.AddUint64(&mmWithdraw.beforeWithdrawCounter, 1)
	defer mm_atomic.AddUint64(&mmWithdraw.afterWithdrawCounter, 1)

	mmWithdraw.t.Helper()

	if mmWithdraw.inspectFuncWithdraw != nil {
		mmWithdraw.inspectFuncWithdraw(ctx, withdrawal)
	}

	mm_params := AccountServiceMockWithdrawParams{ctx, withdrawal}

	// Record call args
	mmWithdraw.WithdrawMock.mutex.Lock()
	mmWithdraw.WithdrawMock.callArgs = append(mmWithdraw.WithdrawMock.callArgs, &mm_params)
	mmWithdraw.WithdrawMock.mutex.Unlock()

	for _, e := range mmWithdraw.WithdrawMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmWithdraw.WithdrawMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWithdraw.WithdrawMock.defaultExpectation.Counter, 1)
		mm_want := mmWithdraw.WithdrawMock.defaultExpectation.params
		mm_want_ptrs := mmWithdraw.WithdrawMock.defaultExpectation.paramPtrs

		mm_got := AccountServiceMockWithdrawParams{ctx, withdrawal}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmWithdraw.t.Errorf("AccountServiceMock.Withdraw got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWithdraw.WithdrawMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.withdrawal != nil && !minimock.Equal(*mm_want_ptrs.withdrawal, mm_got.withdrawal) {
				mmWithdraw.t.Errorf("AccountServiceMock.Withdraw got unexpected parameter withdrawal, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWithdraw.WithdrawMock.defaultExpectation.expectationOrigins.originWithdrawal, *mm_want_ptrs.withdrawal, mm_got.withdrawal, minimock.Diff(*mm_want_ptrs.withdrawal, mm_got.withdrawal))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWithdraw.t.Errorf("AccountServiceMock.Withdraw got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmWithdraw.WithdrawMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWithdraw.WithdrawMock.defaultExpectation.results
		if mm_results == nil {
			mmWithdraw.t.Fatal("No results are set for the AccountServiceMock.Withdraw")
		}
		return (*mm_results).err
	}
	if mmWithdraw.funcWithdraw != nil {
		return mmWithdraw.funcWithdraw(ctx, withdrawal)
	}
	mmWithdraw.t.Fatalf("Unexpected call to AccountServiceMock.Withdraw. %v %v", ctx, withdrawal)
	return
}

// WithdrawAfterCounter returns a count of finished AccountServiceMock.Withdraw invocations
func (mmWithdraw *AccountServiceMock) WithdrawAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWithdraw.afterWithdrawCounter)
}

// WithdrawBeforeCounter returns a count of AccountServiceMock.Withdraw invocations
func (mmWithdraw *AccountServiceMock) WithdrawBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWithdraw.beforeWithdrawCounter)
}

// Calls returns a list of arguments used in each call to AccountServiceMock.Withdraw.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWithdraw *mAccountServiceMockWithdraw) Calls() []*AccountServiceMockWithdrawParams {
	mmWithdraw.mutex.RLock()

	argCopy := make([]*AccountServiceMockWithdrawParams, len(mmWithdraw.callArgs))
	copy(argCopy, mmWithdraw.callArgs)

	mmWithdraw.mutex.RUnlock()

	return argCopy
}

// MinimockWithdrawDone returns true if the count of the Withdraw invocations corresponds
// the number of defined expectations
func (m *AccountServiceMock) MinimockWithdrawDone() bool {
	if m.WithdrawMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.WithdrawMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.WithdrawMock.invocationsDone()
}

// MinimockWithdrawInspect logs each unmet expectation
func (m *AccountServiceMock) MinimockWithdrawInspect() {
	for _, e := range m.WithdrawMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccountServiceMock.Withdraw at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterWithdrawCounter := mm_atomic.LoadUint64(&m.afterWithdrawCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.WithdrawMock.defaultExpectation != nil && afterWithdrawCounter < 1 {
		if m.WithdrawMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccountServiceMock.Withdraw at\n%s", m.WithdrawMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccountServiceMock.Withdraw at\n%s with params: %#v", m.WithdrawMock.defaultExpectation.expectationOrigins.origin, *m.WithdrawMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWithdraw != nil && afterWithdrawCounter < 1 {
		m.t.Errorf("Expected call to AccountServiceMock.Withdraw at\n%s", m.funcWithdrawOrigin)
	}

	if !m.WithdrawMock.invocationsDone() && afterWithdrawCounter > 0 {
		m.t.Errorf("Expected %d calls to AccountServiceMock.Withdraw at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.WithdrawMock.expectedInvocations), m.WithdrawMock.expectedInvocationsOrigin, afterWithdrawCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AccountServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockWithdrawInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AccountServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AccountServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockWithdrawDone()
}
