// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophermart/internal/models"
)

// AccountServiceMock implements mm_balancehandler.AccountService
type AccountServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetAccount          func(ctx context.Context, userID int64) (a1 models.Account, err error)
	funcGetAccountOrigin    string
	inspectFuncGetAccount   func(ctx context.Context, userID int64)
	afterGetAccountCounter  uint64
	beforeGetAccountCounter uint64
	GetAccountMock          mAccountServiceMockGetAccount
}

// NewAccountServiceMock returns a mock for mm_balancehandler.AccountService
func NewAccountServiceMock(t minimock.Tester) *AccountServiceMock {
	m := &AccountServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetAccountMock = mAccountServiceMockGetAccount{mock: m}
	m.GetAccountMock.callArgs = []*AccountServiceMockGetAccountParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAccountServiceMockGetAccount struct {
	optional           bool
	mock               *AccountServiceMock
	defaultExpectation *AccountServiceMockGetAccountExpectation
	expectations       []*AccountServiceMockGetAccountExpectation

	callArgs []*AccountServiceMockGetAccountParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccountServiceMockGetAccountExpectation specifies expectation struct of the AccountService.GetAccount
type AccountServiceMockGetAccountExpectation struct {
	mock               *AccountServiceMock
	params             *AccountServiceMockGetAccountParams
	paramPtrs          *AccountServiceMockGetAccountParamPtrs
	expectationOrigins AccountServiceMockGetAccountExpectationOrigins
	results            *AccountServiceMockGetAccountResults
	returnOrigin       string
	Counter            uint64
}

// AccountServiceMockGetAccountParams contains parameters of the AccountService.GetAccount
type AccountServiceMockGetAccountParams struct {
	ctx    context.Context
	userID int64
}

// AccountServiceMockGetAccountParamPtrs contains pointers to parameters of the AccountService.GetAccount
type AccountServiceMockGetAccountParamPtrs struct {
	ctx    *context.Context
	userID *int64
}

// AccountServiceMockGetAccountResults contains results of the AccountService.GetAccount
type AccountServiceMockGetAccountResults struct {
	a1  models.Account
	err error
}

// AccountServiceMockGetAccountOrigins contains origins of expectations of the AccountService.GetAccount
type AccountServiceMockGetAccountExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetAccount *mAccountServiceMockGetAccount) Optional() *mAccountServiceMockGetAccount {
	mmGetAccount.optional = true
	return mmGetAccount
}

// Expect sets up expected params for AccountService.GetAccount
func (mmGetAccount *mAccountServiceMockGetAccount) Expect(ctx context.Context, userID int64) *mAccountServiceMockGetAccount {
	if mmGetAccount.mock.funcGetAccount != nil {
		mmGetAccount.mock.t.Fatalf("AccountServiceMock.GetAccount mock is already set by Set")
	}

	if mmGetAccount.defaultExpectation == nil {
		mmGetAccount.defaultExpectation = &AccountServiceMockGetAccountExpectation{}
	}

	if mmGetAccount.defaultExpectation.paramPtrs != nil {
		mmGetAccount.mock.t.Fatalf("AccountServiceMock.GetAccount mock is already set by ExpectParams functions")
	}

	mmGetAccount.defaultExpectation.params = &AccountServiceMockGetAccountParams{ctx, userID}
	mmGetAccount.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetAccount.expectations {
		if minimock.Equal(e.params, mmGetAccount.defaultExpectation.params) {
			mmGetAccount.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetAccount.defaultExpectation.params)
		}
	}

	return mmGetAccount
}

// ExpectCtxParam1 sets up expected param ctx for AccountService.GetAccount
func (mmGetAccount *mAccountServiceMockGetAccount) ExpectCtxParam1(ctx context.Context) *mAccountServiceMockGetAccount {
	if mmGetAccount.mock.funcGetAccount != nil {
		mmGetAccount.mock.t.Fatalf("AccountServiceMock.GetAccount mock is already set by Set")
	}

	if mmGetAccount.defaultExpectation == nil {
		mmGetAccount.defaultExpectation = &AccountServiceMockGetAccountExpectation{}
	}

	if mmGetAccount.defaultExpectation.params != nil {
		mmGetAccount.mock.t.Fatalf("AccountServiceMock.GetAccount mock is already set by Expect")
	}

	if mmGetAccount.defaultExpectation.paramPtrs == nil {
		mmGetAccount.defaultExpectation.paramPtrs = &AccountServiceMockGetAccountParamPtrs{}
	}
	mmGetAccount.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetAccount.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetAccount
}

// ExpectUserIDParam2 sets up expected param userID for AccountService.GetAccount
func (mmGetAccount *mAccountServiceMockGetAccount) ExpectUserIDParam2(userID int64) *mAccountServiceMockGetAccount {
	if mmGetAccount.mock.funcGetAccount != nil {
		mmGetAccount.mock.t.Fatalf("AccountServiceMock.GetAccount mock is already set by Set")
	}

	if mmGetAccount.defaultExpectation == nil {
		mmGetAccount.defaultExpectation = &AccountServiceMockGetAccountExpectation{}
	}

	if mmGetAccount.defaultExpectation.params != nil {
		mmGetAccount.mock.t.Fatalf("AccountServiceMock.GetAccount mock is already set by Expect")
	}

	if mmGetAccount.defaultExpectation.paramPtrs == nil {
		mmGetAccount.defaultExpectation.paramPtrs = &AccountServiceMockGetAccountParamPtrs{}
	}
	mmGetAccount.defaultExpectation.paramPtrs.userID = &userID
	mmGetAccount.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetAccount
}

// Inspect accepts an inspector function that has same arguments as the AccountService.GetAccount
func (mmGetAccount *mAccountServiceMockGetAccount) Inspect(f func(ctx context.Context, userID int64)) *mAccountServiceMockGetAccount {
	if mmGetAccount.mock.inspectFuncGetAccount != nil {
		mmGetAccount.mock.t.Fatalf("Inspect function is already set for AccountServiceMock.GetAccount")
	}

	mmGetAccount.mock.inspectFuncGetAccount = f

	return mmGetAccount
}

// Return sets up results that will be returned by AccountService.GetAccount
func (mmGetAccount *mAccountServiceMockGetAccount) Return(a1 models.Account, err error) *AccountServiceMock {
	if mmGetAccount.mock.funcGetAccount != nil {
		mmGetAccount.mock.t.Fatalf("AccountServiceMock.GetAccount mock is already set by Set")
	}

	if mmGetAccount.defaultExpectation == nil {
		mmGetAccount.defaultExpectation = &AccountServiceMockGetAccountExpectation{mock: mmGetAccount.mock}
	}
	mmGetAccount.defaultExpectation.results = &AccountServiceMockGetAccountResults{a1, err}
	mmGetAccount.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetAccount.mock
}

// Set uses given function f to mock the AccountService.GetAccount method
func (mmGetAccount *mAccountServiceMockGetAccount) Set(f func(ctx context.Context, userID int64) (a1 models.Account, err error)) *AccountServiceMock {
	if mmGetAccount.defaultExpectation != nil {
		mmGetAccount.mock.t.Fatalf("Default expectation is already set for the AccountService.GetAccount method")
	}

	if len(mmGetAccount.expectations) > 0 {
		mmGetAccount.mock.t.Fatalf("Some expectations are already set for the AccountService.GetAccount method")
	}

	mmGetAccount.mock.funcGetAccount = f
	mmGetAccount.mock.funcGetAccountOrigin = minimock.CallerInfo(1)
	return mmGetAccount.mock
}

// When sets expectation for the AccountService.GetAccount which will trigger the result defined by the following
// Then helper
func (mmGetAccount *mAccountServiceMockGetAccount) When(ctx context.Context, userID int64) *AccountServiceMockGetAccountExpectation {
	if mmGetAccount.mock.funcGetAccount != nil {
		mmGetAccount.mock.t.Fatalf("AccountServiceMock.GetAccount mock is already set by Set")
	}

	expectation := &AccountServiceMockGetAccountExpectation{
		mock:               mmGetAccount.mock,
		params:             &AccountServiceMockGetAccountParams{ctx, userID},
		expectationOrigins: AccountServiceMockGetAccountExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetAccount.expectations = append(mmGetAccount.expectations, expectation)
	return expectation
}

// Then sets up AccountService.GetAccount return parameters for the expectation previously defined by the When method
func (e *AccountServiceMockGetAccountExpectation) Then(a1 models.Account, err error) *AccountServiceMock {
	e.results = &AccountServiceMockGetAccountResults{a1, err}
	return e.mock
}

// Times sets number of times AccountService.GetAccount should be invoked
func (mmGetAccount *mAccountServiceMockGetAccount) Times(n uint64) *mAccountServiceMockGetAccount {
	if n == 0 {
		mmGetAccount.mock.t.Fatalf("Times of AccountServiceMock.GetAccount mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetAccount.expectedInvocations, n)
	mmGetAccount.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetAccount
}

func (mmGetAccount *mAccountServiceMockGetAccount) invocationsDone() bool {
	if len(mmGetAccount.expectations) == 0 && mmGetAccount.defaultExpectation == nil && mmGetAccount.mock.funcGetAccount == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetAccount.mock.afterGetAccountCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetAccount.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetAccount implements mm_balancehandler.AccountService
func (mmGetAccount *AccountServiceMock) GetAccount(ctx context.Context, userID int64) (a1 models.Account, err error) {
	mm_atomic.AddUint64(&mmGetAccount.beforeGetAccountCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAccount.afterGetAccountCounter, 1)

	mmGetAccount.t.Helper()

	if mmGetAccount.inspectFuncGetAccount != nil {
		mmGetAccount.inspectFuncGetAccount(ctx, userID)
	}

	mm_params := AccountServiceMockGetAccountParams{ctx, userID}

	// Record call args
	mmGetAccount.GetAccountMock.mutex.Lock()
	mmGetAccount.GetAccountMock.callArgs = append(mmGetAccount.GetAccountMock.callArgs, &mm_params)
	mmGetAccount.GetAccountMock.mutex.Unlock()

	for _, e := range mmGetAccount.GetAccountMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.a1, e.results.err
		}
	}

	if mmGetAccount.GetAccountMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAccount.GetAccountMock.defaultExpectation.Counter, 1)
		mm_want := mmGetAccount.GetAccountMock.defaultExpectation.params
		mm_want_ptrs := mmGetAccount.GetAccountMock.defaultExpectation.paramPtrs

		mm_got := AccountServiceMockGetAccountParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetAccount.t.Errorf("AccountServiceMock.GetAccount got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAccount.GetAccountMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetAccount.t.Errorf("AccountServiceMock.GetAccount got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAccount.GetAccountMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetAccount.t.Errorf("AccountServiceMock.GetAccount got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetAccount.GetAccountMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetAccount.GetAccountMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAccount.t.Fatal("No results are set for the AccountServiceMock.GetAccount")
		}
		return (*mm_results).a1, (*mm_results).err
	}
	if mmGetAccount.funcGetAccount != nil {
		return mmGetAccount.funcGetAccount(ctx, userID)
	}
	mmGetAccount.t.Fatalf("Unexpected call to AccountServiceMock.GetAccount. %v %v", ctx, userID)
	return
}

// GetAccountAfterCounter returns a count of finished AccountServiceMock.GetAccount invocations
func (mmGetAccount *AccountServiceMock) GetAccountAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAccount.afterGetAccountCounter)
}

// GetAccountBeforeCounter returns a count of AccountServiceMock.GetAccount invocations
func (mmGetAccount *AccountServiceMock) GetAccountBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAccount.beforeGetAccountCounter)
}

// Calls returns a list of arguments used in each call to AccountServiceMock.GetAccount.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetAccount *mAccountServiceMockGetAccount) Calls() []*AccountServiceMockGetAccountParams {
	mmGetAccount.mutex.RLock()

	argCopy := make([]*AccountServiceMockGetAccountParams, len(mmGetAccount.callArgs))
	copy(argCopy, mmGetAccount.callArgs)

	mmGetAccount.mutex.RUnlock()

	return argCopy
}

// MinimockGetAccountDone returns true if the count of the GetAccount invocations corresponds
// the number of defined expectations
func (m *AccountServiceMock) MinimockGetAccountDone() bool {
	if m.GetAccountMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetAccountMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetAccountMock.invocationsDone()
}

// MinimockGetAccountInspect logs each unmet expectation
func (m *AccountServiceMock) MinimockGetAccountInspect() {
	for _, e := range m.GetAccountMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccountServiceMock.GetAccount at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetAccountCounter := mm_atomic.LoadUint64(&m.afterGetAccountCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetAccountMock.defaultExpectation != nil && afterGetAccountCounter < 1 {
		if m.GetAccountMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccountServiceMock.GetAccount at\n%s", m.GetAccountMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccountServiceMock.GetAccount at\n%s with params: %#v", m.GetAccountMock.defaultExpectation.expectationOrigins.origin, *m.GetAccountMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAccount != nil && afterGetAccountCounter < 1 {
		m.t.Errorf("Expected call to AccountServiceMock.GetAccount at\n%s", m.funcGetAccountOrigin)
	}

	if !m.GetAccountMock.invocationsDone() && afterGetAccountCounter > 0 {
		m.t.Errorf("Expected %d calls to AccountServiceMock.GetAccount at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetAccountMock.expectedInvocations), m.GetAccountMock.expectedInvocationsOrigin, afterGetAccountCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AccountServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetAccountInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AccountServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AccountServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetAccountDone()
}
