// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OrderServiceMock implements mm_addorderhandler.OrderService
type OrderServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddOrder          func(ctx context.Context, orderNumber string, userID int64) (err error)
	funcAddOrderOrigin    string
	inspectFuncAddOrder   func(ctx context.Context, orderNumber string, userID int64)
	afterAddOrderCounter  uint64
	beforeAddOrderCounter uint64
	AddOrderMock          mOrderServiceMockAddOrder
}

// NewOrderServiceMock returns a mock for mm_addorderhandler.OrderService
func NewOrderServiceMock(t minimock.Tester) *OrderServiceMock {
	m := &OrderServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddOrderMock = mOrderServiceMockAddOrder{mock: m}
	m.AddOrderMock.callArgs = []*OrderServiceMockAddOrderParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrderServiceMockAddOrder struct {
	optional           bool
	mock               *OrderServiceMock
	defaultExpectation *OrderServiceMockAddOrderExpectation
	expectations       []*OrderServiceMockAddOrderExpectation

	callArgs []*OrderServiceMockAddOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderServiceMockAddOrderExpectation specifies expectation struct of the OrderService.AddOrder
type OrderServiceMockAddOrderExpectation struct {
	mock               *OrderServiceMock
	params             *OrderServiceMockAddOrderParams
	paramPtrs          *OrderServiceMockAddOrderParamPtrs
	expectationOrigins OrderServiceMockAddOrderExpectationOrigins
	results            *OrderServiceMockAddOrderResults
	returnOrigin       string
	Counter            uint64
}

// OrderServiceMockAddOrderParams contains parameters of the OrderService.AddOrder
type OrderServiceMockAddOrderParams struct {
	ctx         context.Context
	orderNumber string
	userID      int64
}

// OrderServiceMockAddOrderParamPtrs contains pointers to parameters of the OrderService.AddOrder
type OrderServiceMockAddOrderParamPtrs struct {
	ctx         *context.Context
	orderNumber *string
	userID      *int64
}

// OrderServiceMockAddOrderResults contains results of the OrderService.AddOrder
type OrderServiceMockAddOrderResults struct {
	err error
}

// OrderServiceMockAddOrderOrigins contains origins of expectations of the OrderService.AddOrder
type OrderServiceMockAddOrderExpectationOrigins struct {
	origin            string
	originCtx         string
	originOrderNumber string
	originUserID      string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddOrder *mOrderServiceMockAddOrder) Optional() *mOrderServiceMockAddOrder {
	mmAddOrder.optional = true
	return mmAddOrder
}

// Expect sets up expected params for OrderService.AddOrder
func (mmAddOrder *mOrderServiceMockAddOrder) Expect(ctx context.Context, orderNumber string, userID int64) *mOrderServiceMockAddOrder {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &OrderServiceMockAddOrderExpectation{}
	}

	if mmAddOrder.defaultExpectation.paramPtrs != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by ExpectParams functions")
	}

	mmAddOrder.defaultExpectation.params = &OrderServiceMockAddOrderParams{ctx, orderNumber, userID}
	mmAddOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddOrder.expectations {
		if minimock.Equal(e.params, mmAddOrder.defaultExpectation.params) {
			mmAddOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddOrder.defaultExpectation.params)
		}
	}

	return mmAddOrder
}

// ExpectCtxParam1 sets up expected param ctx for OrderService.AddOrder
func (mmAddOrder *mOrderServiceMockAddOrder) ExpectCtxParam1(ctx context.Context) *mOrderServiceMockAddOrder {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &OrderServiceMockAddOrderExpectation{}
	}

	if mmAddOrder.defaultExpectation.params != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Expect")
	}

	if mmAddOrder.defaultExpectation.paramPtrs == nil {
		mmAddOrder.defaultExpectation.paramPtrs = &OrderServiceMockAddOrderParamPtrs{}
	}
	mmAddOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmAddOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAddOrder
}

// ExpectOrderNumberParam2 sets up expected param orderNumber for OrderService.AddOrder
func (mmAddOrder *mOrderServiceMockAddOrder) ExpectOrderNumberParam2(orderNumber string) *mOrderServiceMockAddOrder {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &OrderServiceMockAddOrderExpectation{}
	}

	if mmAddOrder.defaultExpectation.params != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Expect")
	}

	if mmAddOrder.defaultExpectation.paramPtrs == nil {
		mmAddOrder.defaultExpectation.paramPtrs = &OrderServiceMockAddOrderParamPtrs{}
	}
	mmAddOrder.defaultExpectation.paramPtrs.orderNumber = &orderNumber
	mmAddOrder.defaultExpectation.expectationOrigins.originOrderNumber = minimock.CallerInfo(1)

	return mmAddOrder
}

// ExpectUserIDParam3 sets up expected param userID for OrderService.AddOrder
func (mmAddOrder *mOrderServiceMockAddOrder) ExpectUserIDParam3(userID int64) *mOrderServiceMockAddOrder {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &OrderServiceMockAddOrderExpectation{}
	}

	if mmAddOrder.defaultExpectation.params != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Expect")
	}

	if mmAddOrder.defaultExpectation.paramPtrs == nil {
		mmAddOrder.defaultExpectation.paramPtrs = &OrderServiceMockAddOrderParamPtrs{}
	}
	mmAddOrder.defaultExpectation.paramPtrs.userID = &userID
	mmAddOrder.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmAddOrder
}

// Inspect accepts an inspector function that has same arguments as the OrderService.AddOrder
func (mmAddOrder *mOrderServiceMockAddOrder) Inspect(f func(ctx context.Context, orderNumber string, userID int64)) *mOrderServiceMockAddOrder {
	if mmAddOrder.mock.inspectFuncAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("Inspect function is already set for OrderServiceMock.AddOrder")
	}

	mmAddOrder.mock.inspectFuncAddOrder = f

	return mmAddOrder
}

// Return sets up results that will be returned by OrderService.AddOrder
func (mmAddOrder *mOrderServiceMockAddOrder) Return(err error) *OrderServiceMock {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &OrderServiceMockAddOrderExpectation{mock: mmAddOrder.mock}
	}
	mmAddOrder.defaultExpectation.results = &OrderServiceMockAddOrderResults{err}
	mmAddOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddOrder.mock
}

// Set uses given function f to mock the OrderService.AddOrder method
func (mmAddOrder *mOrderServiceMockAddOrder) Set(f func(ctx context.Context, orderNumber string, userID int64) (err error)) *OrderServiceMock {
	if mmAddOrder.defaultExpectation != nil {
		mmAddOrder.mock.t.Fatalf("Default expectation is already set for the OrderService.AddOrder method")
	}

	if len(mmAddOrder.expectations) > 0 {
		mmAddOrder.mock.t.Fatalf("Some expectations are already set for the OrderService.AddOrder method")
	}

	mmAddOrder.mock.funcAddOrder = f
	mmAddOrder.mock.funcAddOrderOrigin = minimock.CallerInfo(1)
	return mmAddOrder.mock
}

// When sets expectation for the OrderService.AddOrder which will trigger the result defined by the following
// Then helper
func (mmAddOrder *mOrderServiceMockAddOrder) When(ctx context.Context, orderNumber string, userID int64) *OrderServiceMockAddOrderExpectation {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("OrderServiceMock.AddOrder mock is already set by Set")
	}

	expectation := &OrderServiceMockAddOrderExpectation{
		mock:               mmAddOrder.mock,
		params:             &OrderServiceMockAddOrderParams{ctx, orderNumber, userID},
		expectationOrigins: OrderServiceMockAddOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddOrder.expectations = append(mmAddOrder.expectations, expectation)
	return expectation
}

// Then sets up OrderService.AddOrder return parameters for the expectation previously defined by the When method
func (e *OrderServiceMockAddOrderExpectation) Then(err error) *OrderServiceMock {
	e.results = &OrderServiceMockAddOrderResults{err}
	return e.mock
}

// Times sets number of times OrderService.AddOrder should be invoked
func (mmAddOrder *mOrderServiceMockAddOrder) Times(n uint64) *mOrderServiceMockAddOrder {
	if n == 0 {
		mmAddOrder.mock.t.Fatalf("Times of OrderServiceMock.AddOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddOrder.expectedInvocations, n)
	mmAddOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddOrder
}

func (mmAddOrder *mOrderServiceMockAddOrder) invocationsDone() bool {
	if len(mmAddOrder.expectations) == 0 && mmAddOrder.defaultExpectation == nil && mmAddOrder.mock.funcAddOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddOrder.mock.afterAddOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddOrder implements mm_addorderhandler.OrderService
func (mmAddOrder *OrderServiceMock) AddOrder(ctx context.Context, orderNumber string, userID int64) (err error) {
	mm_atomic.AddUint64(&mmAddOrder.beforeAddOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmAddOrder.afterAddOrderCounter, 1)

	mmAddOrder.t.Helper()

	if mmAddOrder.inspectFuncAddOrder != nil {
		mmAddOrder.inspectFuncAddOrder(ctx, orderNumber, userID)
	}

	mm_params := OrderServiceMockAddOrderParams{ctx, orderNumber, userID}

	// Record call args
	mmAddOrder.AddOrderMock.mutex.Lock()
	mmAddOrder.AddOrderMock.callArgs = append(mmAddOrder.AddOrderMock.callArgs, &mm_params)
	mmAddOrder.AddOrderMock.mutex.Unlock()

	for _, e := range mmAddOrder.AddOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddOrder.AddOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddOrder.AddOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmAddOrder.AddOrderMock.defaultExpectation.params
		mm_want_ptrs := mmAddOrder.AddOrderMock.defaultExpectation.paramPtrs

		mm_got := OrderServiceMockAddOrderParams{ctx, orderNumber, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAddOrder.t.Errorf("OrderServiceMock.AddOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddOrder.AddOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderNumber != nil && !minimock.Equal(*mm_want_ptrs.orderNumber, mm_got.orderNumber) {
				mmAddOrder.t.Errorf("OrderServiceMock.AddOrder got unexpected parameter orderNumber, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddOrder.AddOrderMock.defaultExpectation.expectationOrigins.originOrderNumber, *mm_want_ptrs.orderNumber, mm_got.orderNumber, minimock.Diff(*mm_want_ptrs.orderNumber, mm_got.orderNumber))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmAddOrder.t.Errorf("OrderServiceMock.AddOrder got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddOrder.AddOrderMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddOrder.t.Errorf("OrderServiceMock.AddOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddOrder.AddOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddOrder.AddOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmAddOrder.t.Fatal("No results are set for the OrderServiceMock.AddOrder")
		}
		return (*mm_results).err
	}
	if mmAddOrder.funcAddOrder != nil {
		return mmAddOrder.funcAddOrder(ctx, orderNumber, userID)
	}
	mmAddOrder.t.Fatalf("Unexpected call to OrderServiceMock.AddOrder. %v %v %v", ctx, orderNumber, userID)
	return
}

// AddOrderAfterCounter returns a count of finished OrderServiceMock.AddOrder invocations
func (mmAddOrder *OrderServiceMock) AddOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddOrder.afterAddOrderCounter)
}

// AddOrderBeforeCounter returns a count of OrderServiceMock.AddOrder invocations
func (mmAddOrder *OrderServiceMock) AddOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddOrder.beforeAddOrderCounter)
}

// Calls returns a list of arguments used in each call to OrderServiceMock.AddOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddOrder *mOrderServiceMockAddOrder) Calls() []*OrderServiceMockAddOrderParams {
	mmAddOrder.mutex.RLock()

	argCopy := make([]*OrderServiceMockAddOrderParams, len(mmAddOrder.callArgs))
	copy(argCopy, mmAddOrder.callArgs)

	mmAddOrder.mutex.RUnlock()

	return argCopy
}

// MinimockAddOrderDone returns true if the count of the AddOrder invocations corresponds
// the number of defined expectations
func (m *OrderServiceMock) MinimockAddOrderDone() bool {
	if m.AddOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddOrderMock.invocationsDone()
}

// MinimockAddOrderInspect logs each unmet expectation
func (m *OrderServiceMock) MinimockAddOrderInspect() {
	for _, e := range m.AddOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderServiceMock.AddOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddOrderCounter := mm_atomic.LoadUint64(&m.afterAddOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddOrderMock.defaultExpectation != nil && afterAddOrderCounter < 1 {
		if m.AddOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderServiceMock.AddOrder at\n%s", m.AddOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderServiceMock.AddOrder at\n%s with params: %#v", m.AddOrderMock.defaultExpectation.expectationOrigins.origin, *m.AddOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddOrder != nil && afterAddOrderCounter < 1 {
		m.t.Errorf("Expected call to OrderServiceMock.AddOrder at\n%s", m.funcAddOrderOrigin)
	}

	if !m.AddOrderMock.invocationsDone() && afterAddOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderServiceMock.AddOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddOrderMock.expectedInvocations), m.AddOrderMock.expectedInvocationsOrigin, afterAddOrderCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddOrderInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddOrderDone()
}
