// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophermart/internal/models"
)

// WithdrawalServiceMock implements mm_withdrawals.WithdrawalService
type WithdrawalServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetWithdrawalsByUser          func(ctx context.Context, userID int64) (wa1 []models.Withdrawal, err error)
	funcGetWithdrawalsByUserOrigin    string
	inspectFuncGetWithdrawalsByUser   func(ctx context.Context, userID int64)
	afterGetWithdrawalsByUserCounter  uint64
	beforeGetWithdrawalsByUserCounter uint64
	GetWithdrawalsByUserMock          mWithdrawalServiceMockGetWithdrawalsByUser
}

// NewWithdrawalServiceMock returns a mock for mm_withdrawals.WithdrawalService
func NewWithdrawalServiceMock(t minimock.Tester) *WithdrawalServiceMock {
	m := &WithdrawalServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetWithdrawalsByUserMock = mWithdrawalServiceMockGetWithdrawalsByUser{mock: m}
	m.GetWithdrawalsByUserMock.callArgs = []*WithdrawalServiceMockGetWithdrawalsByUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mWithdrawalServiceMockGetWithdrawalsByUser struct {
	optional           bool
	mock               *WithdrawalServiceMock
	defaultExpectation *WithdrawalServiceMockGetWithdrawalsByUserExpectation
	expectations       []*WithdrawalServiceMockGetWithdrawalsByUserExpectation

	callArgs []*WithdrawalServiceMockGetWithdrawalsByUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// WithdrawalServiceMockGetWithdrawalsByUserExpectation specifies expectation struct of the WithdrawalService.GetWithdrawalsByUser
type WithdrawalServiceMockGetWithdrawalsByUserExpectation struct {
	mock               *WithdrawalServiceMock
	params             *WithdrawalServiceMockGetWithdrawalsByUserParams
	paramPtrs          *WithdrawalServiceMockGetWithdrawalsByUserParamPtrs
	expectationOrigins WithdrawalServiceMockGetWithdrawalsByUserExpectationOrigins
	results            *WithdrawalServiceMockGetWithdrawalsByUserResults
	returnOrigin       string
	Counter            uint64
}

// WithdrawalServiceMockGetWithdrawalsByUserParams contains parameters of the WithdrawalService.GetWithdrawalsByUser
type WithdrawalServiceMockGetWithdrawalsByUserParams struct {
	ctx    context.Context
	userID int64
}

// WithdrawalServiceMockGetWithdrawalsByUserParamPtrs contains pointers to parameters of the WithdrawalService.GetWithdrawalsByUser
type WithdrawalServiceMockGetWithdrawalsByUserParamPtrs struct {
	ctx    *context.Context
	userID *int64
}

// WithdrawalServiceMockGetWithdrawalsByUserResults contains results of the WithdrawalService.GetWithdrawalsByUser
type WithdrawalServiceMockGetWithdrawalsByUserResults struct {
	wa1 []models.Withdrawal
	err error
}

// WithdrawalServiceMockGetWithdrawalsByUserOrigins contains origins of expectations of the WithdrawalService.GetWithdrawalsByUser
type WithdrawalServiceMockGetWithdrawalsByUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) Optional() *mWithdrawalServiceMockGetWithdrawalsByUser {
	mmGetWithdrawalsByUser.optional = true
	return mmGetWithdrawalsByUser
}

// Expect sets up expected params for WithdrawalService.GetWithdrawalsByUser
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) Expect(ctx context.Context, userID int64) *mWithdrawalServiceMockGetWithdrawalsByUser {
	if mmGetWithdrawalsByUser.mock.funcGetWithdrawalsByUser != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("WithdrawalServiceMock.GetWithdrawalsByUser mock is already set by Set")
	}

	if mmGetWithdrawalsByUser.defaultExpectation == nil {
		mmGetWithdrawalsByUser.defaultExpectation = &WithdrawalServiceMockGetWithdrawalsByUserExpectation{}
	}

	if mmGetWithdrawalsByUser.defaultExpectation.paramPtrs != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("WithdrawalServiceMock.GetWithdrawalsByUser mock is already set by ExpectParams functions")
	}

	mmGetWithdrawalsByUser.defaultExpectation.params = &WithdrawalServiceMockGetWithdrawalsByUserParams{ctx, userID}
	mmGetWithdrawalsByUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetWithdrawalsByUser.expectations {
		if minimock.Equal(e.params, mmGetWithdrawalsByUser.defaultExpectation.params) {
			mmGetWithdrawalsByUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetWithdrawalsByUser.defaultExpectation.params)
		}
	}

	return mmGetWithdrawalsByUser
}

// ExpectCtxParam1 sets up expected param ctx for WithdrawalService.GetWithdrawalsByUser
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) ExpectCtxParam1(ctx context.Context) *mWithdrawalServiceMockGetWithdrawalsByUser {
	if mmGetWithdrawalsByUser.mock.funcGetWithdrawalsByUser != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("WithdrawalServiceMock.GetWithdrawalsByUser mock is already set by Set")
	}

	if mmGetWithdrawalsByUser.defaultExpectation == nil {
		mmGetWithdrawalsByUser.defaultExpectation = &WithdrawalServiceMockGetWithdrawalsByUserExpectation{}
	}

	if mmGetWithdrawalsByUser.defaultExpectation.params != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("WithdrawalServiceMock.GetWithdrawalsByUser mock is already set by Expect")
	}

	if mmGetWithdrawalsByUser.defaultExpectation.paramPtrs == nil {
		mmGetWithdrawalsByUser.defaultExpectation.paramPtrs = &WithdrawalServiceMockGetWithdrawalsByUserParamPtrs{}
	}
	mmGetWithdrawalsByUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetWithdrawalsByUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetWithdrawalsByUser
}

// ExpectUserIDParam2 sets up expected param userID for WithdrawalService.GetWithdrawalsByUser
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) ExpectUserIDParam2(userID int64) *mWithdrawalServiceMockGetWithdrawalsByUser {
	if mmGetWithdrawalsByUser.mock.funcGetWithdrawalsByUser != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("WithdrawalServiceMock.GetWithdrawalsByUser mock is already set by Set")
	}

	if mmGetWithdrawalsByUser.defaultExpectation == nil {
		mmGetWithdrawalsByUser.defaultExpectation = &WithdrawalServiceMockGetWithdrawalsByUserExpectation{}
	}

	if mmGetWithdrawalsByUser.defaultExpectation.params != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("WithdrawalServiceMock.GetWithdrawalsByUser mock is already set by Expect")
	}

	if mmGetWithdrawalsByUser.defaultExpectation.paramPtrs == nil {
		mmGetWithdrawalsByUser.defaultExpectation.paramPtrs = &WithdrawalServiceMockGetWithdrawalsByUserParamPtrs{}
	}
	mmGetWithdrawalsByUser.defaultExpectation.paramPtrs.userID = &userID
	mmGetWithdrawalsByUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetWithdrawalsByUser
}

// Inspect accepts an inspector function that has same arguments as the WithdrawalService.GetWithdrawalsByUser
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) Inspect(f func(ctx context.Context, userID int64)) *mWithdrawalServiceMockGetWithdrawalsByUser {
	if mmGetWithdrawalsByUser.mock.inspectFuncGetWithdrawalsByUser != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("Inspect function is already set for WithdrawalServiceMock.GetWithdrawalsByUser")
	}

	mmGetWithdrawalsByUser.mock.inspectFuncGetWithdrawalsByUser = f

	return mmGetWithdrawalsByUser
}

// Return sets up results that will be returned by WithdrawalService.GetWithdrawalsByUser
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) Return(wa1 []models.Withdrawal, err error) *WithdrawalServiceMock {
	if mmGetWithdrawalsByUser.mock.funcGetWithdrawalsByUser != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("WithdrawalServiceMock.GetWithdrawalsByUser mock is already set by Set")
	}

	if mmGetWithdrawalsByUser.defaultExpectation == nil {
		mmGetWithdrawalsByUser.defaultExpectation = &WithdrawalServiceMockGetWithdrawalsByUserExpectation{mock: mmGetWithdrawalsByUser.mock}
	}
	mmGetWithdrawalsByUser.defaultExpectation.results = &WithdrawalServiceMockGetWithdrawalsByUserResults{wa1, err}
	mmGetWithdrawalsByUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetWithdrawalsByUser.mock
}

// Set uses given function f to mock the WithdrawalService.GetWithdrawalsByUser method
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) Set(f func(ctx context.Context, userID int64) (wa1 []models.Withdrawal, err error)) *WithdrawalServiceMock {
	if mmGetWithdrawalsByUser.defaultExpectation != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("Default expectation is already set for the WithdrawalService.GetWithdrawalsByUser method")
	}

	if len(mmGetWithdrawalsByUser.expectations) > 0 {
		mmGetWithdrawalsByUser.mock.t.Fatalf("Some expectations are already set for the WithdrawalService.GetWithdrawalsByUser method")
	}

	mmGetWithdrawalsByUser.mock.funcGetWithdrawalsByUser = f
	mmGetWithdrawalsByUser.mock.funcGetWithdrawalsByUserOrigin = minimock.CallerInfo(1)
	return mmGetWithdrawalsByUser.mock
}

// When sets expectation for the WithdrawalService.GetWithdrawalsByUser which will trigger the result defined by the following
// Then helper
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) When(ctx context.Context, userID int64) *WithdrawalServiceMockGetWithdrawalsByUserExpectation {
	if mmGetWithdrawalsByUser.mock.funcGetWithdrawalsByUser != nil {
		mmGetWithdrawalsByUser.mock.t.Fatalf("WithdrawalServiceMock.GetWithdrawalsByUser mock is already set by Set")
	}

	expectation := &WithdrawalServiceMockGetWithdrawalsByUserExpectation{
		mock:               mmGetWithdrawalsByUser.mock,
		params:             &WithdrawalServiceMockGetWithdrawalsByUserParams{ctx, userID},
		expectationOrigins: WithdrawalServiceMockGetWithdrawalsByUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetWithdrawalsByUser.expectations = append(mmGetWithdrawalsByUser.expectations, expectation)
	return expectation
}

// Then sets up WithdrawalService.GetWithdrawalsByUser return parameters for the expectation previously defined by the When method
func (e *WithdrawalServiceMockGetWithdrawalsByUserExpectation) Then(wa1 []models.Withdrawal, err error) *WithdrawalServiceMock {
	e.results = &WithdrawalServiceMockGetWithdrawalsByUserResults{wa1, err}
	return e.mock
}

// Times sets number of times WithdrawalService.GetWithdrawalsByUser should be invoked
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) Times(n uint64) *mWithdrawalServiceMockGetWithdrawalsByUser {
	if n == 0 {
		mmGetWithdrawalsByUser.mock.t.Fatalf("Times of WithdrawalServiceMock.GetWithdrawalsByUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetWithdrawalsByUser.expectedInvocations, n)
	mmGetWithdrawalsByUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetWithdrawalsByUser
}

func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) invocationsDone() bool {
	if len(mmGetWithdrawalsByUser.expectations) == 0 && mmGetWithdrawalsByUser.defaultExpectation == nil && mmGetWithdrawalsByUser.mock.funcGetWithdrawalsByUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetWithdrawalsByUser.mock.afterGetWithdrawalsByUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetWithdrawalsByUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetWithdrawalsByUser implements mm_withdrawals.WithdrawalService
func (mmGetWithdrawalsByUser *WithdrawalServiceMock) GetWithdrawalsByUser(ctx context.Context, userID int64) (wa1 []models.Withdrawal, err error) {
	mm_atomic.AddUint64(&mmGetWithdrawalsByUser.beforeGetWithdrawalsByUserCounter, 1)
	defer mm_atomic.AddUint64(&mmGetWithdrawalsByUser.afterGetWithdrawalsByUserCounter, 1)

	mmGetWithdrawalsByUser.t.Helper()

	if mmGetWithdrawalsByUser.inspectFuncGetWithdrawalsByUser != nil {
		mmGetWithdrawalsByUser.inspectFuncGetWithdrawalsByUser(ctx, userID)
	}

	mm_params := WithdrawalServiceMockGetWithdrawalsByUserParams{ctx, userID}

	// Record call args
	mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.mutex.Lock()
	mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.callArgs = append(mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.callArgs, &mm_params)
	mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.mutex.Unlock()

	for _, e := range mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.wa1, e.results.err
		}
	}

	if mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.defaultExpectation.Counter, 1)
		mm_want := mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.defaultExpectation.params
		mm_want_ptrs := mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.defaultExpectation.paramPtrs

		mm_got := WithdrawalServiceMockGetWithdrawalsByUserParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetWithdrawalsByUser.t.Errorf("WithdrawalServiceMock.GetWithdrawalsByUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetWithdrawalsByUser.t.Errorf("WithdrawalServiceMock.GetWithdrawalsByUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetWithdrawalsByUser.t.Errorf("WithdrawalServiceMock.GetWithdrawalsByUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetWithdrawalsByUser.GetWithdrawalsByUserMock.defaultExpectation.results
		if mm_results == nil {
			mmGetWithdrawalsByUser.t.Fatal("No results are set for the WithdrawalServiceMock.GetWithdrawalsByUser")
		}
		return (*mm_results).wa1, (*mm_results).err
	}
	if mmGetWithdrawalsByUser.funcGetWithdrawalsByUser != nil {
		return mmGetWithdrawalsByUser.funcGetWithdrawalsByUser(ctx, userID)
	}
	mmGetWithdrawalsByUser.t.Fatalf("Unexpected call to WithdrawalServiceMock.GetWithdrawalsByUser. %v %v", ctx, userID)
	return
}

// GetWithdrawalsByUserAfterCounter returns a count of finished WithdrawalServiceMock.GetWithdrawalsByUser invocations
func (mmGetWithdrawalsByUser *WithdrawalServiceMock) GetWithdrawalsByUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetWithdrawalsByUser.afterGetWithdrawalsByUserCounter)
}

// GetWithdrawalsByUserBeforeCounter returns a count of WithdrawalServiceMock.GetWithdrawalsByUser invocations
func (mmGetWithdrawalsByUser *WithdrawalServiceMock) GetWithdrawalsByUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetWithdrawalsByUser.beforeGetWithdrawalsByUserCounter)
}

// Calls returns a list of arguments used in each call to WithdrawalServiceMock.GetWithdrawalsByUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetWithdrawalsByUser *mWithdrawalServiceMockGetWithdrawalsByUser) Calls() []*WithdrawalServiceMockGetWithdrawalsByUserParams {
	mmGetWithdrawalsByUser.mutex.RLock()

	argCopy := make([]*WithdrawalServiceMockGetWithdrawalsByUserParams, len(mmGetWithdrawalsByUser.callArgs))
	copy(argCopy, mmGetWithdrawalsByUser.callArgs)

	mmGetWithdrawalsByUser.mutex.RUnlock()

	return argCopy
}

// MinimockGetWithdrawalsByUserDone returns true if the count of the GetWithdrawalsByUser invocations corresponds
// the number of defined expectations
func (m *WithdrawalServiceMock) MinimockGetWithdrawalsByUserDone() bool {
	if m.GetWithdrawalsByUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetWithdrawalsByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetWithdrawalsByUserMock.invocationsDone()
}

// MinimockGetWithdrawalsByUserInspect logs each unmet expectation
func (m *WithdrawalServiceMock) MinimockGetWithdrawalsByUserInspect() {
	for _, e := range m.GetWithdrawalsByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to WithdrawalServiceMock.GetWithdrawalsByUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetWithdrawalsByUserCounter := mm_atomic.LoadUint64(&m.afterGetWithdrawalsByUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetWithdrawalsByUserMock.defaultExpectation != nil && afterGetWithdrawalsByUserCounter < 1 {
		if m.GetWithdrawalsByUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to WithdrawalServiceMock.GetWithdrawalsByUser at\n%s", m.GetWithdrawalsByUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to WithdrawalServiceMock.GetWithdrawalsByUser at\n%s with params: %#v", m.GetWithdrawalsByUserMock.defaultExpectation.expectationOrigins.origin, *m.GetWithdrawalsByUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetWithdrawalsByUser != nil && afterGetWithdrawalsByUserCounter < 1 {
		m.t.Errorf("Expected call to WithdrawalServiceMock.GetWithdrawalsByUser at\n%s", m.funcGetWithdrawalsByUserOrigin)
	}

	if !m.GetWithdrawalsByUserMock.invocationsDone() && afterGetWithdrawalsByUserCounter > 0 {
		m.t.Errorf("Expected %d calls to WithdrawalServiceMock.GetWithdrawalsByUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetWithdrawalsByUserMock.expectedInvocations), m.GetWithdrawalsByUserMock.expectedInvocationsOrigin, afterGetWithdrawalsByUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *WithdrawalServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetWithdrawalsByUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *WithdrawalServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *WithdrawalServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetWithdrawalsByUserDone()
}
