// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophermart/internal/models"
)

// AccualClientMock implements mm_worker.AccualClient
type AccualClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddOrder          func(ctx context.Context, orderNumber string) (err error)
	funcAddOrderOrigin    string
	inspectFuncAddOrder   func(ctx context.Context, orderNumber string)
	afterAddOrderCounter  uint64
	beforeAddOrderCounter uint64
	AddOrderMock          mAccualClientMockAddOrder

	funcGetOrderStatus          func(ctx context.Context, orderNumber string) (a1 models.AccrualResponse, err error)
	funcGetOrderStatusOrigin    string
	inspectFuncGetOrderStatus   func(ctx context.Context, orderNumber string)
	afterGetOrderStatusCounter  uint64
	beforeGetOrderStatusCounter uint64
	GetOrderStatusMock          mAccualClientMockGetOrderStatus
}

// NewAccualClientMock returns a mock for mm_worker.AccualClient
func NewAccualClientMock(t minimock.Tester) *AccualClientMock {
	m := &AccualClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddOrderMock = mAccualClientMockAddOrder{mock: m}
	m.AddOrderMock.callArgs = []*AccualClientMockAddOrderParams{}

	m.GetOrderStatusMock = mAccualClientMockGetOrderStatus{mock: m}
	m.GetOrderStatusMock.callArgs = []*AccualClientMockGetOrderStatusParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAccualClientMockAddOrder struct {
	optional           bool
	mock               *AccualClientMock
	defaultExpectation *AccualClientMockAddOrderExpectation
	expectations       []*AccualClientMockAddOrderExpectation

	callArgs []*AccualClientMockAddOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccualClientMockAddOrderExpectation specifies expectation struct of the AccualClient.AddOrder
type AccualClientMockAddOrderExpectation struct {
	mock               *AccualClientMock
	params             *AccualClientMockAddOrderParams
	paramPtrs          *AccualClientMockAddOrderParamPtrs
	expectationOrigins AccualClientMockAddOrderExpectationOrigins
	results            *AccualClientMockAddOrderResults
	returnOrigin       string
	Counter            uint64
}

// AccualClientMockAddOrderParams contains parameters of the AccualClient.AddOrder
type AccualClientMockAddOrderParams struct {
	ctx         context.Context
	orderNumber string
}

// AccualClientMockAddOrderParamPtrs contains pointers to parameters of the AccualClient.AddOrder
type AccualClientMockAddOrderParamPtrs struct {
	ctx         *context.Context
	orderNumber *string
}

// AccualClientMockAddOrderResults contains results of the AccualClient.AddOrder
type AccualClientMockAddOrderResults struct {
	err error
}

// AccualClientMockAddOrderOrigins contains origins of expectations of the AccualClient.AddOrder
type AccualClientMockAddOrderExpectationOrigins struct {
	origin            string
	originCtx         string
	originOrderNumber string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddOrder *mAccualClientMockAddOrder) Optional() *mAccualClientMockAddOrder {
	mmAddOrder.optional = true
	return mmAddOrder
}

// Expect sets up expected params for AccualClient.AddOrder
func (mmAddOrder *mAccualClientMockAddOrder) Expect(ctx context.Context, orderNumber string) *mAccualClientMockAddOrder {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("AccualClientMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &AccualClientMockAddOrderExpectation{}
	}

	if mmAddOrder.defaultExpectation.paramPtrs != nil {
		mmAddOrder.mock.t.Fatalf("AccualClientMock.AddOrder mock is already set by ExpectParams functions")
	}

	mmAddOrder.defaultExpectation.params = &AccualClientMockAddOrderParams{ctx, orderNumber}
	mmAddOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddOrder.expectations {
		if minimock.Equal(e.params, mmAddOrder.defaultExpectation.params) {
			mmAddOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddOrder.defaultExpectation.params)
		}
	}

	return mmAddOrder
}

// ExpectCtxParam1 sets up expected param ctx for AccualClient.AddOrder
func (mmAddOrder *mAccualClientMockAddOrder) ExpectCtxParam1(ctx context.Context) *mAccualClientMockAddOrder {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("AccualClientMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &AccualClientMockAddOrderExpectation{}
	}

	if mmAddOrder.defaultExpectation.params != nil {
		mmAddOrder.mock.t.Fatalf("AccualClientMock.AddOrder mock is already set by Expect")
	}

	if mmAddOrder.defaultExpectation.paramPtrs == nil {
		mmAddOrder.defaultExpectation.paramPtrs = &AccualClientMockAddOrderParamPtrs{}
	}
	mmAddOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmAddOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAddOrder
}

// ExpectOrderNumberParam2 sets up expected param orderNumber for AccualClient.AddOrder
func (mmAddOrder *mAccualClientMockAddOrder) ExpectOrderNumberParam2(orderNumber string) *mAccualClientMockAddOrder {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("AccualClientMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &AccualClientMockAddOrderExpectation{}
	}

	if mmAddOrder.defaultExpectation.params != nil {
		mmAddOrder.mock.t.Fatalf("AccualClientMock.AddOrder mock is already set by Expect")
	}

	if mmAddOrder.defaultExpectation.paramPtrs == nil {
		mmAddOrder.defaultExpectation.paramPtrs = &AccualClientMockAddOrderParamPtrs{}
	}
	mmAddOrder.defaultExpectation.paramPtrs.orderNumber = &orderNumber
	mmAddOrder.defaultExpectation.expectationOrigins.originOrderNumber = minimock.CallerInfo(1)

	return mmAddOrder
}

// Inspect accepts an inspector function that has same arguments as the AccualClient.AddOrder
func (mmAddOrder *mAccualClientMockAddOrder) Inspect(f func(ctx context.Context, orderNumber string)) *mAccualClientMockAddOrder {
	if mmAddOrder.mock.inspectFuncAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("Inspect function is already set for AccualClientMock.AddOrder")
	}

	mmAddOrder.mock.inspectFuncAddOrder = f

	return mmAddOrder
}

// Return sets up results that will be returned by AccualClient.AddOrder
func (mmAddOrder *mAccualClientMockAddOrder) Return(err error) *AccualClientMock {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("AccualClientMock.AddOrder mock is already set by Set")
	}

	if mmAddOrder.defaultExpectation == nil {
		mmAddOrder.defaultExpectation = &AccualClientMockAddOrderExpectation{mock: mmAddOrder.mock}
	}
	mmAddOrder.defaultExpectation.results = &AccualClientMockAddOrderResults{err}
	mmAddOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddOrder.mock
}

// Set uses given function f to mock the AccualClient.AddOrder method
func (mmAddOrder *mAccualClientMockAddOrder) Set(f func(ctx context.Context, orderNumber string) (err error)) *AccualClientMock {
	if mmAddOrder.defaultExpectation != nil {
		mmAddOrder.mock.t.Fatalf("Default expectation is already set for the AccualClient.AddOrder method")
	}

	if len(mmAddOrder.expectations) > 0 {
		mmAddOrder.mock.t.Fatalf("Some expectations are already set for the AccualClient.AddOrder method")
	}

	mmAddOrder.mock.funcAddOrder = f
	mmAddOrder.mock.funcAddOrderOrigin = minimock.CallerInfo(1)
	return mmAddOrder.mock
}

// When sets expectation for the AccualClient.AddOrder which will trigger the result defined by the following
// Then helper
func (mmAddOrder *mAccualClientMockAddOrder) When(ctx context.Context, orderNumber string) *AccualClientMockAddOrderExpectation {
	if mmAddOrder.mock.funcAddOrder != nil {
		mmAddOrder.mock.t.Fatalf("AccualClientMock.AddOrder mock is already set by Set")
	}

	expectation := &AccualClientMockAddOrderExpectation{
		mock:               mmAddOrder.mock,
		params:             &AccualClientMockAddOrderParams{ctx, orderNumber},
		expectationOrigins: AccualClientMockAddOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddOrder.expectations = append(mmAddOrder.expectations, expectation)
	return expectation
}

// Then sets up AccualClient.AddOrder return parameters for the expectation previously defined by the When method
func (e *AccualClientMockAddOrderExpectation) Then(err error) *AccualClientMock {
	e.results = &AccualClientMockAddOrderResults{err}
	return e.mock
}

// Times sets number of times AccualClient.AddOrder should be invoked
func (mmAddOrder *mAccualClientMockAddOrder) Times(n uint64) *mAccualClientMockAddOrder {
	if n == 0 {
		mmAddOrder.mock.t.Fatalf("Times of AccualClientMock.AddOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddOrder.expectedInvocations, n)
	mmAddOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddOrder
}

func (mmAddOrder *mAccualClientMockAddOrder) invocationsDone() bool {
	if len(mmAddOrder.expectations) == 0 && mmAddOrder.defaultExpectation == nil && mmAddOrder.mock.funcAddOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddOrder.mock.afterAddOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddOrder implements mm_worker.AccualClient
func (mmAddOrder *AccualClientMock) AddOrder(ctx context.Context, orderNumber string) (err error) {
	mm_atomic.AddUint64(&mmAddOrder.beforeAddOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmAddOrder.afterAddOrderCounter, 1)

	mmAddOrder.t.Helper()

	if mmAddOrder.inspectFuncAddOrder != nil {
		mmAddOrder.inspectFuncAddOrder(ctx, orderNumber)
	}

	mm_params := AccualClientMockAddOrderParams{ctx, orderNumber}

	// Record call args
	mmAddOrder.AddOrderMock.mutex.Lock()
	mmAddOrder.AddOrderMock.callArgs = append(mmAddOrder.AddOrderMock.callArgs, &mm_params)
	mmAddOrder.AddOrderMock.mutex.Unlock()

	for _, e := range mmAddOrder.AddOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddOrder.AddOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddOrder.AddOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmAddOrder.AddOrderMock.defaultExpectation.params
		mm_want_ptrs := mmAddOrder.AddOrderMock.defaultExpectation.paramPtrs

		mm_got := AccualClientMockAddOrderParams{ctx, orderNumber}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAddOrder.t.Errorf("AccualClientMock.AddOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddOrder.AddOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderNumber != nil && !minimock.Equal(*mm_want_ptrs.orderNumber, mm_got.orderNumber) {
				mmAddOrder.t.Errorf("AccualClientMock.AddOrder got unexpected parameter orderNumber, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddOrder.AddOrderMock.defaultExpectation.expectationOrigins.originOrderNumber, *mm_want_ptrs.orderNumber, mm_got.orderNumber, minimock.Diff(*mm_want_ptrs.orderNumber, mm_got.orderNumber))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddOrder.t.Errorf("AccualClientMock.AddOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddOrder.AddOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddOrder.AddOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmAddOrder.t.Fatal("No results are set for the AccualClientMock.AddOrder")
		}
		return (*mm_results).err
	}
	if mmAddOrder.funcAddOrder != nil {
		return mmAddOrder.funcAddOrder(ctx, orderNumber)
	}
	mmAddOrder.t.Fatalf("Unexpected call to AccualClientMock.AddOrder. %v %v", ctx, orderNumber)
	return
}

// AddOrderAfterCounter returns a count of finished AccualClientMock.AddOrder invocations
func (mmAddOrder *AccualClientMock) AddOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddOrder.afterAddOrderCounter)
}

// AddOrderBeforeCounter returns a count of AccualClientMock.AddOrder invocations
func (mmAddOrder *AccualClientMock) AddOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddOrder.beforeAddOrderCounter)
}

// Calls returns a list of arguments used in each call to AccualClientMock.AddOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddOrder *mAccualClientMockAddOrder) Calls() []*AccualClientMockAddOrderParams {
	mmAddOrder.mutex.RLock()

	argCopy := make([]*AccualClientMockAddOrderParams, len(mmAddOrder.callArgs))
	copy(argCopy, mmAddOrder.callArgs)

	mmAddOrder.mutex.RUnlock()

	return argCopy
}

// MinimockAddOrderDone returns true if the count of the AddOrder invocations corresponds
// the number of defined expectations
func (m *AccualClientMock) MinimockAddOrderDone() bool {
	if m.AddOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddOrderMock.invocationsDone()
}

// MinimockAddOrderInspect logs each unmet expectation
func (m *AccualClientMock) MinimockAddOrderInspect() {
	for _, e := range m.AddOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccualClientMock.AddOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddOrderCounter := mm_atomic.LoadUint64(&m.afterAddOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddOrderMock.defaultExpectation != nil && afterAddOrderCounter < 1 {
		if m.AddOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccualClientMock.AddOrder at\n%s", m.AddOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccualClientMock.AddOrder at\n%s with params: %#v", m.AddOrderMock.defaultExpectation.expectationOrigins.origin, *m.AddOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddOrder != nil && afterAddOrderCounter < 1 {
		m.t.Errorf("Expected call to AccualClientMock.AddOrder at\n%s", m.funcAddOrderOrigin)
	}

	if !m.AddOrderMock.invocationsDone() && afterAddOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to AccualClientMock.AddOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddOrderMock.expectedInvocations), m.AddOrderMock.expectedInvocationsOrigin, afterAddOrderCounter)
	}
}

type mAccualClientMockGetOrderStatus struct {
	optional           bool
	mock               *AccualClientMock
	defaultExpectation *AccualClientMockGetOrderStatusExpectation
	expectations       []*AccualClientMockGetOrderStatusExpectation

	callArgs []*AccualClientMockGetOrderStatusParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccualClientMockGetOrderStatusExpectation specifies expectation struct of the AccualClient.GetOrderStatus
type AccualClientMockGetOrderStatusExpectation struct {
	mock               *AccualClientMock
	params             *AccualClientMockGetOrderStatusParams
	paramPtrs          *AccualClientMockGetOrderStatusParamPtrs
	expectationOrigins AccualClientMockGetOrderStatusExpectationOrigins
	results            *AccualClientMockGetOrderStatusResults
	returnOrigin       string
	Counter            uint64
}

// AccualClientMockGetOrderStatusParams contains parameters of the AccualClient.GetOrderStatus
type AccualClientMockGetOrderStatusParams struct {
	ctx         context.Context
	orderNumber string
}

// AccualClientMockGetOrderStatusParamPtrs contains pointers to parameters of the AccualClient.GetOrderStatus
type AccualClientMockGetOrderStatusParamPtrs struct {
	ctx         *context.Context
	orderNumber *string
}

// AccualClientMockGetOrderStatusResults contains results of the AccualClient.GetOrderStatus
type AccualClientMockGetOrderStatusResults struct {
	a1  models.AccrualResponse
	err error
}

// AccualClientMockGetOrderStatusOrigins contains origins of expectations of the AccualClient.GetOrderStatus
type AccualClientMockGetOrderStatusExpectationOrigins struct {
	origin            string
	originCtx         string
	originOrderNumber string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) Optional() *mAccualClientMockGetOrderStatus {
	mmGetOrderStatus.optional = true
	return mmGetOrderStatus
}

// Expect sets up expected params for AccualClient.GetOrderStatus
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) Expect(ctx context.Context, orderNumber string) *mAccualClientMockGetOrderStatus {
	if mmGetOrderStatus.mock.funcGetOrderStatus != nil {
		mmGetOrderStatus.mock.t.Fatalf("AccualClientMock.GetOrderStatus mock is already set by Set")
	}

	if mmGetOrderStatus.defaultExpectation == nil {
		mmGetOrderStatus.defaultExpectation = &AccualClientMockGetOrderStatusExpectation{}
	}

	if mmGetOrderStatus.defaultExpectation.paramPtrs != nil {
		mmGetOrderStatus.mock.t.Fatalf("AccualClientMock.GetOrderStatus mock is already set by ExpectParams functions")
	}

	mmGetOrderStatus.defaultExpectation.params = &AccualClientMockGetOrderStatusParams{ctx, orderNumber}
	mmGetOrderStatus.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetOrderStatus.expectations {
		if minimock.Equal(e.params, mmGetOrderStatus.defaultExpectation.params) {
			mmGetOrderStatus.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetOrderStatus.defaultExpectation.params)
		}
	}

	return mmGetOrderStatus
}

// ExpectCtxParam1 sets up expected param ctx for AccualClient.GetOrderStatus
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) ExpectCtxParam1(ctx context.Context) *mAccualClientMockGetOrderStatus {
	if mmGetOrderStatus.mock.funcGetOrderStatus != nil {
		mmGetOrderStatus.mock.t.Fatalf("AccualClientMock.GetOrderStatus mock is already set by Set")
	}

	if mmGetOrderStatus.defaultExpectation == nil {
		mmGetOrderStatus.defaultExpectation = &AccualClientMockGetOrderStatusExpectation{}
	}

	if mmGetOrderStatus.defaultExpectation.params != nil {
		mmGetOrderStatus.mock.t.Fatalf("AccualClientMock.GetOrderStatus mock is already set by Expect")
	}

	if mmGetOrderStatus.defaultExpectation.paramPtrs == nil {
		mmGetOrderStatus.defaultExpectation.paramPtrs = &AccualClientMockGetOrderStatusParamPtrs{}
	}
	mmGetOrderStatus.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetOrderStatus.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetOrderStatus
}

// ExpectOrderNumberParam2 sets up expected param orderNumber for AccualClient.GetOrderStatus
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) ExpectOrderNumberParam2(orderNumber string) *mAccualClientMockGetOrderStatus {
	if mmGetOrderStatus.mock.funcGetOrderStatus != nil {
		mmGetOrderStatus.mock.t.Fatalf("AccualClientMock.GetOrderStatus mock is already set by Set")
	}

	if mmGetOrderStatus.defaultExpectation == nil {
		mmGetOrderStatus.defaultExpectation = &AccualClientMockGetOrderStatusExpectation{}
	}

	if mmGetOrderStatus.defaultExpectation.params != nil {
		mmGetOrderStatus.mock.t.Fatalf("AccualClientMock.GetOrderStatus mock is already set by Expect")
	}

	if mmGetOrderStatus.defaultExpectation.paramPtrs == nil {
		mmGetOrderStatus.defaultExpectation.paramPtrs = &AccualClientMockGetOrderStatusParamPtrs{}
	}
	mmGetOrderStatus.defaultExpectation.paramPtrs.orderNumber = &orderNumber
	mmGetOrderStatus.defaultExpectation.expectationOrigins.originOrderNumber = minimock.CallerInfo(1)

	return mmGetOrderStatus
}

// Inspect accepts an inspector function that has same arguments as the AccualClient.GetOrderStatus
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) Inspect(f func(ctx context.Context, orderNumber string)) *mAccualClientMockGetOrderStatus {
	if mmGetOrderStatus.mock.inspectFuncGetOrderStatus != nil {
		mmGetOrderStatus.mock.t.Fatalf("Inspect function is already set for AccualClientMock.GetOrderStatus")
	}

	mmGetOrderStatus.mock.inspectFuncGetOrderStatus = f

	return mmGetOrderStatus
}

// Return sets up results that will be returned by AccualClient.GetOrderStatus
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) Return(a1 models.AccrualResponse, err error) *AccualClientMock {
	if mmGetOrderStatus.mock.funcGetOrderStatus != nil {
		mmGetOrderStatus.mock.t.Fatalf("AccualClientMock.GetOrderStatus mock is already set by Set")
	}

	if mmGetOrderStatus.defaultExpectation == nil {
		mmGetOrderStatus.defaultExpectation = &AccualClientMockGetOrderStatusExpectation{mock: mmGetOrderStatus.mock}
	}
	mmGetOrderStatus.defaultExpectation.results = &AccualClientMockGetOrderStatusResults{a1, err}
	mmGetOrderStatus.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetOrderStatus.mock
}

// Set uses given function f to mock the AccualClient.GetOrderStatus method
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) Set(f func(ctx context.Context, orderNumber string) (a1 models.AccrualResponse, err error)) *AccualClientMock {
	if mmGetOrderStatus.defaultExpectation != nil {
		mmGetOrderStatus.mock.t.Fatalf("Default expectation is already set for the AccualClient.GetOrderStatus method")
	}

	if len(mmGetOrderStatus.expectations) > 0 {
		mmGetOrderStatus.mock.t.Fatalf("Some expectations are already set for the AccualClient.GetOrderStatus method")
	}

	mmGetOrderStatus.mock.funcGetOrderStatus = f
	mmGetOrderStatus.mock.funcGetOrderStatusOrigin = minimock.CallerInfo(1)
	return mmGetOrderStatus.mock
}

// When sets expectation for the AccualClient.GetOrderStatus which will trigger the result defined by the following
// Then helper
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) When(ctx context.Context, orderNumber string) *AccualClientMockGetOrderStatusExpectation {
	if mmGetOrderStatus.mock.funcGetOrderStatus != nil {
		mmGetOrderStatus.mock.t.Fatalf("AccualClientMock.GetOrderStatus mock is already set by Set")
	}

	expectation := &AccualClientMockGetOrderStatusExpectation{
		mock:               mmGetOrderStatus.mock,
		params:             &AccualClientMockGetOrderStatusParams{ctx, orderNumber},
		expectationOrigins: AccualClientMockGetOrderStatusExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetOrderStatus.expectations = append(mmGetOrderStatus.expectations, expectation)
	return expectation
}

// Then sets up AccualClient.GetOrderStatus return parameters for the expectation previously defined by the When method
func (e *AccualClientMockGetOrderStatusExpectation) Then(a1 models.AccrualResponse, err error) *AccualClientMock {
	e.results = &AccualClientMockGetOrderStatusResults{a1, err}
	return e.mock
}

// Times sets number of times AccualClient.GetOrderStatus should be invoked
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) Times(n uint64) *mAccualClientMockGetOrderStatus {
	if n == 0 {
		mmGetOrderStatus.mock.t.Fatalf("Times of AccualClientMock.GetOrderStatus mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetOrderStatus.expectedInvocations, n)
	mmGetOrderStatus.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetOrderStatus
}

func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) invocationsDone() bool {
	if len(mmGetOrderStatus.expectations) == 0 && mmGetOrderStatus.defaultExpectation == nil && mmGetOrderStatus.mock.funcGetOrderStatus == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetOrderStatus.mock.afterGetOrderStatusCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetOrderStatus.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetOrderStatus implements mm_worker.AccualClient
func (mmGetOrderStatus *AccualClientMock) GetOrderStatus(ctx context.Context, orderNumber string) (a1 models.AccrualResponse, err error) {
	mm_atomic.AddUint64(&mmGetOrderStatus.beforeGetOrderStatusCounter, 1)
	defer mm_atomic.AddUint64(&mmGetOrderStatus.afterGetOrderStatusCounter, 1)

	mmGetOrderStatus.t.Helper()

	if mmGetOrderStatus.inspectFuncGetOrderStatus != nil {
		mmGetOrderStatus.inspectFuncGetOrderStatus(ctx, orderNumber)
	}

	mm_params := AccualClientMockGetOrderStatusParams{ctx, orderNumber}

	// Record call args
	mmGetOrderStatus.GetOrderStatusMock.mutex.Lock()
	mmGetOrderStatus.GetOrderStatusMock.callArgs = append(mmGetOrderStatus.GetOrderStatusMock.callArgs, &mm_params)
	mmGetOrderStatus.GetOrderStatusMock.mutex.Unlock()

	for _, e := range mmGetOrderStatus.GetOrderStatusMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.a1, e.results.err
		}
	}

	if mmGetOrderStatus.GetOrderStatusMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetOrderStatus.GetOrderStatusMock.defaultExpectation.Counter, 1)
		mm_want := mmGetOrderStatus.GetOrderStatusMock.defaultExpectation.params
		mm_want_ptrs := mmGetOrderStatus.GetOrderStatusMock.defaultExpectation.paramPtrs

		mm_got := AccualClientMockGetOrderStatusParams{ctx, orderNumber}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetOrderStatus.t.Errorf("AccualClientMock.GetOrderStatus got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetOrderStatus.GetOrderStatusMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderNumber != nil && !minimock.Equal(*mm_want_ptrs.orderNumber, mm_got.orderNumber) {
				mmGetOrderStatus.t.Errorf("AccualClientMock.GetOrderStatus got unexpected parameter orderNumber, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetOrderStatus.GetOrderStatusMock.defaultExpectation.expectationOrigins.originOrderNumber, *mm_want_ptrs.orderNumber, mm_got.orderNumber, minimock.Diff(*mm_want_ptrs.orderNumber, mm_got.orderNumber))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetOrderStatus.t.Errorf("AccualClientMock.GetOrderStatus got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetOrderStatus.GetOrderStatusMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetOrderStatus.GetOrderStatusMock.defaultExpectation.results
		if mm_results == nil {
			mmGetOrderStatus.t.Fatal("No results are set for the AccualClientMock.GetOrderStatus")
		}
		return (*mm_results).a1, (*mm_results).err
	}
	if mmGetOrderStatus.funcGetOrderStatus != nil {
		return mmGetOrderStatus.funcGetOrderStatus(ctx, orderNumber)
	}
	mmGetOrderStatus.t.Fatalf("Unexpected call to AccualClientMock.GetOrderStatus. %v %v", ctx, orderNumber)
	return
}

// GetOrderStatusAfterCounter returns a count of finished AccualClientMock.GetOrderStatus invocations
func (mmGetOrderStatus *AccualClientMock) GetOrderStatusAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetOrderStatus.afterGetOrderStatusCounter)
}

// GetOrderStatusBeforeCounter returns a count of AccualClientMock.GetOrderStatus invocations
func (mmGetOrderStatus *AccualClientMock) GetOrderStatusBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetOrderStatus.beforeGetOrderStatusCounter)
}

// Calls returns a list of arguments used in each call to AccualClientMock.GetOrderStatus.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetOrderStatus *mAccualClientMockGetOrderStatus) Calls() []*AccualClientMockGetOrderStatusParams {
	mmGetOrderStatus.mutex.RLock()

	argCopy := make([]*AccualClientMockGetOrderStatusParams, len(mmGetOrderStatus.callArgs))
	copy(argCopy, mmGetOrderStatus.callArgs)

	mmGetOrderStatus.mutex.RUnlock()

	return argCopy
}

// MinimockGetOrderStatusDone returns true if the count of the GetOrderStatus invocations corresponds
// the number of defined expectations
func (m *AccualClientMock) MinimockGetOrderStatusDone() bool {
	if m.GetOrderStatusMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetOrderStatusMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetOrderStatusMock.invocationsDone()
}

// MinimockGetOrderStatusInspect logs each unmet expectation
func (m *AccualClientMock) MinimockGetOrderStatusInspect() {
	for _, e := range m.GetOrderStatusMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccualClientMock.GetOrderStatus at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetOrderStatusCounter := mm_atomic.LoadUint64(&m.afterGetOrderStatusCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetOrderStatusMock.defaultExpectation != nil && afterGetOrderStatusCounter < 1 {
		if m.GetOrderStatusMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccualClientMock.GetOrderStatus at\n%s", m.GetOrderStatusMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccualClientMock.GetOrderStatus at\n%s with params: %#v", m.GetOrderStatusMock.defaultExpectation.expectationOrigins.origin, *m.GetOrderStatusMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetOrderStatus != nil && afterGetOrderStatusCounter < 1 {
		m.t.Errorf("Expected call to AccualClientMock.GetOrderStatus at\n%s", m.funcGetOrderStatusOrigin)
	}

	if !m.GetOrderStatusMock.invocationsDone() && afterGetOrderStatusCounter > 0 {
		m.t.Errorf("Expected %d calls to AccualClientMock.GetOrderStatus at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetOrderStatusMock.expectedInvocations), m.GetOrderStatusMock.expectedInvocationsOrigin, afterGetOrderStatusCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AccualClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddOrderInspect()

			m.MinimockGetOrderStatusInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AccualClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AccualClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddOrderDone() &&
		m.MinimockGetOrderStatusDone()
}
