// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OrderServiceMock implements mm_worker.OrderService
type OrderServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetOrdersForCheckingStatus          func(ctx context.Context) (sa1 []string, err error)
	funcGetOrdersForCheckingStatusOrigin    string
	inspectFuncGetOrdersForCheckingStatus   func(ctx context.Context)
	afterGetOrdersForCheckingStatusCounter  uint64
	beforeGetOrdersForCheckingStatusCounter uint64
	GetOrdersForCheckingStatusMock          mOrderServiceMockGetOrdersForCheckingStatus

	funcUpdateOrder          func(ctx context.Context, orderNumber string, status string, accrual int64) (err error)
	funcUpdateOrderOrigin    string
	inspectFuncUpdateOrder   func(ctx context.Context, orderNumber string, status string, accrual int64)
	afterUpdateOrderCounter  uint64
	beforeUpdateOrderCounter uint64
	UpdateOrderMock          mOrderServiceMockUpdateOrder
}

// NewOrderServiceMock returns a mock for mm_worker.OrderService
func NewOrderServiceMock(t minimock.Tester) *OrderServiceMock {
	m := &OrderServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetOrdersForCheckingStatusMock = mOrderServiceMockGetOrdersForCheckingStatus{mock: m}
	m.GetOrdersForCheckingStatusMock.callArgs = []*OrderServiceMockGetOrdersForCheckingStatusParams{}

	m.UpdateOrderMock = mOrderServiceMockUpdateOrder{mock: m}
	m.UpdateOrderMock.callArgs = []*OrderServiceMockUpdateOrderParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrderServiceMockGetOrdersForCheckingStatus struct {
	optional           bool
	mock               *OrderServiceMock
	defaultExpectation *OrderServiceMockGetOrdersForCheckingStatusExpectation
	expectations       []*OrderServiceMockGetOrdersForCheckingStatusExpectation

	callArgs []*OrderServiceMockGetOrdersForCheckingStatusParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderServiceMockGetOrdersForCheckingStatusExpectation specifies expectation struct of the OrderService.GetOrdersForCheckingStatus
type OrderServiceMockGetOrdersForCheckingStatusExpectation struct {
	mock               *OrderServiceMock
	params             *OrderServiceMockGetOrdersForCheckingStatusParams
	paramPtrs          *OrderServiceMockGetOrdersForCheckingStatusParamPtrs
	expectationOrigins OrderServiceMockGetOrdersForCheckingStatusExpectationOrigins
	results            *OrderServiceMockGetOrdersForCheckingStatusResults
	returnOrigin       string
	Counter            uint64
}

// OrderServiceMockGetOrdersForCheckingStatusParams contains parameters of the OrderService.GetOrdersForCheckingStatus
type OrderServiceMockGetOrdersForCheckingStatusParams struct {
	ctx context.Context
}

// OrderServiceMockGetOrdersForCheckingStatusParamPtrs contains pointers to parameters of the OrderService.GetOrdersForCheckingStatus
type OrderServiceMockGetOrdersForCheckingStatusParamPtrs struct {
	ctx *context.Context
}

// OrderServiceMockGetOrdersForCheckingStatusResults contains results of the OrderService.GetOrdersForCheckingStatus
type OrderServiceMockGetOrdersForCheckingStatusResults struct {
	sa1 []string
	err error
}

// OrderServiceMockGetOrdersForCheckingStatusOrigins contains origins of expectations of the OrderService.GetOrdersForCheckingStatus
type OrderServiceMockGetOrdersForCheckingStatusExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) Optional() *mOrderServiceMockGetOrdersForCheckingStatus {
	mmGetOrdersForCheckingStatus.optional = true
	return mmGetOrdersForCheckingStatus
}

// Expect sets up expected params for OrderService.GetOrdersForCheckingStatus
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) Expect(ctx context.Context) *mOrderServiceMockGetOrdersForCheckingStatus {
	if mmGetOrdersForCheckingStatus.mock.funcGetOrdersForCheckingStatus != nil {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("OrderServiceMock.GetOrdersForCheckingStatus mock is already set by Set")
	}

	if mmGetOrdersForCheckingStatus.defaultExpectation == nil {
		mmGetOrdersForCheckingStatus.defaultExpectation = &OrderServiceMockGetOrdersForCheckingStatusExpectation{}
	}

	if mmGetOrdersForCheckingStatus.defaultExpectation.paramPtrs != nil {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("OrderServiceMock.GetOrdersForCheckingStatus mock is already set by ExpectParams functions")
	}

	mmGetOrdersForCheckingStatus.defaultExpectation.params = &OrderServiceMockGetOrdersForCheckingStatusParams{ctx}
	mmGetOrdersForCheckingStatus.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetOrdersForCheckingStatus.expectations {
		if minimock.Equal(e.params, mmGetOrdersForCheckingStatus.defaultExpectation.params) {
			mmGetOrdersForCheckingStatus.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetOrdersForCheckingStatus.defaultExpectation.params)
		}
	}

	return mmGetOrdersForCheckingStatus
}

// ExpectCtxParam1 sets up expected param ctx for OrderService.GetOrdersForCheckingStatus
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) ExpectCtxParam1(ctx context.Context) *mOrderServiceMockGetOrdersForCheckingStatus {
	if mmGetOrdersForCheckingStatus.mock.funcGetOrdersForCheckingStatus != nil {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("OrderServiceMock.GetOrdersForCheckingStatus mock is already set by Set")
	}

	if mmGetOrdersForCheckingStatus.defaultExpectation == nil {
		mmGetOrdersForCheckingStatus.defaultExpectation = &OrderServiceMockGetOrdersForCheckingStatusExpectation{}
	}

	if mmGetOrdersForCheckingStatus.defaultExpectation.params != nil {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("OrderServiceMock.GetOrdersForCheckingStatus mock is already set by Expect")
	}

	if mmGetOrdersForCheckingStatus.defaultExpectation.paramPtrs == nil {
		mmGetOrdersForCheckingStatus.defaultExpectation.paramPtrs = &OrderServiceMockGetOrdersForCheckingStatusParamPtrs{}
	}
	mmGetOrdersForCheckingStatus.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetOrdersForCheckingStatus.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetOrdersForCheckingStatus
}

// Inspect accepts an inspector function that has same arguments as the OrderService.GetOrdersForCheckingStatus
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) Inspect(f func(ctx context.Context)) *mOrderServiceMockGetOrdersForCheckingStatus {
	if mmGetOrdersForCheckingStatus.mock.inspectFuncGetOrdersForCheckingStatus != nil {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("Inspect function is already set for OrderServiceMock.GetOrdersForCheckingStatus")
	}

	mmGetOrdersForCheckingStatus.mock.inspectFuncGetOrdersForCheckingStatus = f

	return mmGetOrdersForCheckingStatus
}

// Return sets up results that will be returned by OrderService.GetOrdersForCheckingStatus
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) Return(sa1 []string, err error) *OrderServiceMock {
	if mmGetOrdersForCheckingStatus.mock.funcGetOrdersForCheckingStatus != nil {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("OrderServiceMock.GetOrdersForCheckingStatus mock is already set by Set")
	}

	if mmGetOrdersForCheckingStatus.defaultExpectation == nil {
		mmGetOrdersForCheckingStatus.defaultExpectation = &OrderServiceMockGetOrdersForCheckingStatusExpectation{mock: mmGetOrdersForCheckingStatus.mock}
	}
	mmGetOrdersForCheckingStatus.defaultExpectation.results = &OrderServiceMockGetOrdersForCheckingStatusResults{sa1, err}
	mmGetOrdersForCheckingStatus.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetOrdersForCheckingStatus.mock
}

// Set uses given function f to mock the OrderService.GetOrdersForCheckingStatus method
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) Set(f func(ctx context.Context) (sa1 []string, err error)) *OrderServiceMock {
	if mmGetOrdersForCheckingStatus.defaultExpectation != nil {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("Default expectation is already set for the OrderService.GetOrdersForCheckingStatus method")
	}

	if len(mmGetOrdersForCheckingStatus.expectations) > 0 {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("Some expectations are already set for the OrderService.GetOrdersForCheckingStatus method")
	}

	mmGetOrdersForCheckingStatus.mock.funcGetOrdersForCheckingStatus = f
	mmGetOrdersForCheckingStatus.mock.funcGetOrdersForCheckingStatusOrigin = minimock.CallerInfo(1)
	return mmGetOrdersForCheckingStatus.mock
}

// When sets expectation for the OrderService.GetOrdersForCheckingStatus which will trigger the result defined by the following
// Then helper
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) When(ctx context.Context) *OrderServiceMockGetOrdersForCheckingStatusExpectation {
	if mmGetOrdersForCheckingStatus.mock.funcGetOrdersForCheckingStatus != nil {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("OrderServiceMock.GetOrdersForCheckingStatus mock is already set by Set")
	}

	expectation := &OrderServiceMockGetOrdersForCheckingStatusExpectation{
		mock:               mmGetOrdersForCheckingStatus.mock,
		params:             &OrderServiceMockGetOrdersForCheckingStatusParams{ctx},
		expectationOrigins: OrderServiceMockGetOrdersForCheckingStatusExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetOrdersForCheckingStatus.expectations = append(mmGetOrdersForCheckingStatus.expectations, expectation)
	return expectation
}

// Then sets up OrderService.GetOrdersForCheckingStatus return parameters for the expectation previously defined by the When method
func (e *OrderServiceMockGetOrdersForCheckingStatusExpectation) Then(sa1 []string, err error) *OrderServiceMock {
	e.results = &OrderServiceMockGetOrdersForCheckingStatusResults{sa1, err}
	return e.mock
}

// Times sets number of times OrderService.GetOrdersForCheckingStatus should be invoked
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) Times(n uint64) *mOrderServiceMockGetOrdersForCheckingStatus {
	if n == 0 {
		mmGetOrdersForCheckingStatus.mock.t.Fatalf("Times of OrderServiceMock.GetOrdersForCheckingStatus mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetOrdersForCheckingStatus.expectedInvocations, n)
	mmGetOrdersForCheckingStatus.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetOrdersForCheckingStatus
}

func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) invocationsDone() bool {
	if len(mmGetOrdersForCheckingStatus.expectations) == 0 && mmGetOrdersForCheckingStatus.defaultExpectation == nil && mmGetOrdersForCheckingStatus.mock.funcGetOrdersForCheckingStatus == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetOrdersForCheckingStatus.mock.afterGetOrdersForCheckingStatusCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetOrdersForCheckingStatus.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetOrdersForCheckingStatus implements mm_worker.OrderService
func (mmGetOrdersForCheckingStatus *OrderServiceMock) GetOrdersForCheckingStatus(ctx context.Context) (sa1 []string, err error) {
	mm_atomic.AddUint64(&mmGetOrdersForCheckingStatus.beforeGetOrdersForCheckingStatusCounter, 1)
	defer mm_atomic.AddUint64(&mmGetOrdersForCheckingStatus.afterGetOrdersForCheckingStatusCounter, 1)

	mmGetOrdersForCheckingStatus.t.Helper()

	if mmGetOrdersForCheckingStatus.inspectFuncGetOrdersForCheckingStatus != nil {
		mmGetOrdersForCheckingStatus.inspectFuncGetOrdersForCheckingStatus(ctx)
	}

	mm_params := OrderServiceMockGetOrdersForCheckingStatusParams{ctx}

	// Record call args
	mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.mutex.Lock()
	mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.callArgs = append(mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.callArgs, &mm_params)
	mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.mutex.Unlock()

	for _, e := range mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.defaultExpectation.Counter, 1)
		mm_want := mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.defaultExpectation.params
		mm_want_ptrs := mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.defaultExpectation.paramPtrs

		mm_got := OrderServiceMockGetOrdersForCheckingStatusParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetOrdersForCheckingStatus.t.Errorf("OrderServiceMock.GetOrdersForCheckingStatus got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetOrdersForCheckingStatus.t.Errorf("OrderServiceMock.GetOrdersForCheckingStatus got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetOrdersForCheckingStatus.GetOrdersForCheckingStatusMock.defaultExpectation.results
		if mm_results == nil {
			mmGetOrdersForCheckingStatus.t.Fatal("No results are set for the OrderServiceMock.GetOrdersForCheckingStatus")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmGetOrdersForCheckingStatus.funcGetOrdersForCheckingStatus != nil {
		return mmGetOrdersForCheckingStatus.funcGetOrdersForCheckingStatus(ctx)
	}
	mmGetOrdersForCheckingStatus.t.Fatalf("Unexpected call to OrderServiceMock.GetOrdersForCheckingStatus. %v", ctx)
	return
}

// GetOrdersForCheckingStatusAfterCounter returns a count of finished OrderServiceMock.GetOrdersForCheckingStatus invocations
func (mmGetOrdersForCheckingStatus *OrderServiceMock) GetOrdersForCheckingStatusAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetOrdersForCheckingStatus.afterGetOrdersForCheckingStatusCounter)
}

// GetOrdersForCheckingStatusBeforeCounter returns a count of OrderServiceMock.GetOrdersForCheckingStatus invocations
func (mmGetOrdersForCheckingStatus *OrderServiceMock) GetOrdersForCheckingStatusBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetOrdersForCheckingStatus.beforeGetOrdersForCheckingStatusCounter)
}

// Calls returns a list of arguments used in each call to OrderServiceMock.GetOrdersForCheckingStatus.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetOrdersForCheckingStatus *mOrderServiceMockGetOrdersForCheckingStatus) Calls() []*OrderServiceMockGetOrdersForCheckingStatusParams {
	mmGetOrdersForCheckingStatus.mutex.RLock()

	argCopy := make([]*OrderServiceMockGetOrdersForCheckingStatusParams, len(mmGetOrdersForCheckingStatus.callArgs))
	copy(argCopy, mmGetOrdersForCheckingStatus.callArgs)

	mmGetOrdersForCheckingStatus.mutex.RUnlock()

	return argCopy
}

// MinimockGetOrdersForCheckingStatusDone returns true if the count of the GetOrdersForCheckingStatus invocations corresponds
// the number of defined expectations
func (m *OrderServiceMock) MinimockGetOrdersForCheckingStatusDone() bool {
	if m.GetOrdersForCheckingStatusMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetOrdersForCheckingStatusMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetOrdersForCheckingStatusMock.invocationsDone()
}

// MinimockGetOrdersForCheckingStatusInspect logs each unmet expectation
func (m *OrderServiceMock) MinimockGetOrdersForCheckingStatusInspect() {
	for _, e := range m.GetOrdersForCheckingStatusMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderServiceMock.GetOrdersForCheckingStatus at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetOrdersForCheckingStatusCounter := mm_atomic.LoadUint64(&m.afterGetOrdersForCheckingStatusCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetOrdersForCheckingStatusMock.defaultExpectation != nil && afterGetOrdersForCheckingStatusCounter < 1 {
		if m.GetOrdersForCheckingStatusMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderServiceMock.GetOrdersForCheckingStatus at\n%s", m.GetOrdersForCheckingStatusMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderServiceMock.GetOrdersForCheckingStatus at\n%s with params: %#v", m.GetOrdersForCheckingStatusMock.defaultExpectation.expectationOrigins.origin, *m.GetOrdersForCheckingStatusMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetOrdersForCheckingStatus != nil && afterGetOrdersForCheckingStatusCounter < 1 {
		m.t.Errorf("Expected call to OrderServiceMock.GetOrdersForCheckingStatus at\n%s", m.funcGetOrdersForCheckingStatusOrigin)
	}

	if !m.GetOrdersForCheckingStatusMock.invocationsDone() && afterGetOrdersForCheckingStatusCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderServiceMock.GetOrdersForCheckingStatus at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetOrdersForCheckingStatusMock.expectedInvocations), m.GetOrdersForCheckingStatusMock.expectedInvocationsOrigin, afterGetOrdersForCheckingStatusCounter)
	}
}

type mOrderServiceMockUpdateOrder struct {
	optional           bool
	mock               *OrderServiceMock
	defaultExpectation *OrderServiceMockUpdateOrderExpectation
	expectations       []*OrderServiceMockUpdateOrderExpectation

	callArgs []*OrderServiceMockUpdateOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderServiceMockUpdateOrderExpectation specifies expectation struct of the OrderService.UpdateOrder
type OrderServiceMockUpdateOrderExpectation struct {
	mock               *OrderServiceMock
	params             *OrderServiceMockUpdateOrderParams
	paramPtrs          *OrderServiceMockUpdateOrderParamPtrs
	expectationOrigins OrderServiceMockUpdateOrderExpectationOrigins
	results            *OrderServiceMockUpdateOrderResults
	returnOrigin       string
	Counter            uint64
}

// OrderServiceMockUpdateOrderParams contains parameters of the OrderService.UpdateOrder
type OrderServiceMockUpdateOrderParams struct {
	ctx         context.Context
	orderNumber string
	status      string
	accrual     int64
}

// OrderServiceMockUpdateOrderParamPtrs contains pointers to parameters of the OrderService.UpdateOrder
type OrderServiceMockUpdateOrderParamPtrs struct {
	ctx         *context.Context
	orderNumber *string
	status      *string
	accrual     *int64
}

// OrderServiceMockUpdateOrderResults contains results of the OrderService.UpdateOrder
type OrderServiceMockUpdateOrderResults struct {
	err error
}

// OrderServiceMockUpdateOrderOrigins contains origins of expectations of the OrderService.UpdateOrder
type OrderServiceMockUpdateOrderExpectationOrigins struct {
	origin            string
	originCtx         string
	originOrderNumber string
	originStatus      string
	originAccrual     string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) Optional() *mOrderServiceMockUpdateOrder {
	mmUpdateOrder.optional = true
	return mmUpdateOrder
}

// Expect sets up expected params for OrderService.UpdateOrder
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) Expect(ctx context.Context, orderNumber string, status string, accrual int64) *mOrderServiceMockUpdateOrder {
	if mmUpdateOrder.mock.funcUpdateOrder != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Set")
	}

	if mmUpdateOrder.defaultExpectation == nil {
		mmUpdateOrder.defaultExpectation = &OrderServiceMockUpdateOrderExpectation{}
	}

	if mmUpdateOrder.defaultExpectation.paramPtrs != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by ExpectParams functions")
	}

	mmUpdateOrder.defaultExpectation.params = &OrderServiceMockUpdateOrderParams{ctx, orderNumber, status, accrual}
	mmUpdateOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateOrder.expectations {
		if minimock.Equal(e.params, mmUpdateOrder.defaultExpectation.params) {
			mmUpdateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateOrder.defaultExpectation.params)
		}
	}

	return mmUpdateOrder
}

// ExpectCtxParam1 sets up expected param ctx for OrderService.UpdateOrder
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) ExpectCtxParam1(ctx context.Context) *mOrderServiceMockUpdateOrder {
	if mmUpdateOrder.mock.funcUpdateOrder != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Set")
	}

	if mmUpdateOrder.defaultExpectation == nil {
		mmUpdateOrder.defaultExpectation = &OrderServiceMockUpdateOrderExpectation{}
	}

	if mmUpdateOrder.defaultExpectation.params != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Expect")
	}

	if mmUpdateOrder.defaultExpectation.paramPtrs == nil {
		mmUpdateOrder.defaultExpectation.paramPtrs = &OrderServiceMockUpdateOrderParamPtrs{}
	}
	mmUpdateOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateOrder
}

// ExpectOrderNumberParam2 sets up expected param orderNumber for OrderService.UpdateOrder
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) ExpectOrderNumberParam2(orderNumber string) *mOrderServiceMockUpdateOrder {
	if mmUpdateOrder.mock.funcUpdateOrder != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Set")
	}

	if mmUpdateOrder.defaultExpectation == nil {
		mmUpdateOrder.defaultExpectation = &OrderServiceMockUpdateOrderExpectation{}
	}

	if mmUpdateOrder.defaultExpectation.params != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Expect")
	}

	if mmUpdateOrder.defaultExpectation.paramPtrs == nil {
		mmUpdateOrder.defaultExpectation.paramPtrs = &OrderServiceMockUpdateOrderParamPtrs{}
	}
	mmUpdateOrder.defaultExpectation.paramPtrs.orderNumber = &orderNumber
	mmUpdateOrder.defaultExpectation.expectationOrigins.originOrderNumber = minimock.CallerInfo(1)

	return mmUpdateOrder
}

// ExpectStatusParam3 sets up expected param status for OrderService.UpdateOrder
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) ExpectStatusParam3(status string) *mOrderServiceMockUpdateOrder {
	if mmUpdateOrder.mock.funcUpdateOrder != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Set")
	}

	if mmUpdateOrder.defaultExpectation == nil {
		mmUpdateOrder.defaultExpectation = &OrderServiceMockUpdateOrderExpectation{}
	}

	if mmUpdateOrder.defaultExpectation.params != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Expect")
	}

	if mmUpdateOrder.defaultExpectation.paramPtrs == nil {
		mmUpdateOrder.defaultExpectation.paramPtrs = &OrderServiceMockUpdateOrderParamPtrs{}
	}
	mmUpdateOrder.defaultExpectation.paramPtrs.status = &status
	mmUpdateOrder.defaultExpectation.expectationOrigins.originStatus = minimock.CallerInfo(1)

	return mmUpdateOrder
}

// ExpectAccrualParam4 sets up expected param accrual for OrderService.UpdateOrder
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) ExpectAccrualParam4(accrual int64) *mOrderServiceMockUpdateOrder {
	if mmUpdateOrder.mock.funcUpdateOrder != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Set")
	}

	if mmUpdateOrder.defaultExpectation == nil {
		mmUpdateOrder.defaultExpectation = &OrderServiceMockUpdateOrderExpectation{}
	}

	if mmUpdateOrder.defaultExpectation.params != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Expect")
	}

	if mmUpdateOrder.defaultExpectation.paramPtrs == nil {
		mmUpdateOrder.defaultExpectation.paramPtrs = &OrderServiceMockUpdateOrderParamPtrs{}
	}
	mmUpdateOrder.defaultExpectation.paramPtrs.accrual = &accrual
	mmUpdateOrder.defaultExpectation.expectationOrigins.originAccrual = minimock.CallerInfo(1)

	return mmUpdateOrder
}

// Inspect accepts an inspector function that has same arguments as the OrderService.UpdateOrder
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) Inspect(f func(ctx context.Context, orderNumber string, status string, accrual int64)) *mOrderServiceMockUpdateOrder {
	if mmUpdateOrder.mock.inspectFuncUpdateOrder != nil {
		mmUpdateOrder.mock.t.Fatalf("Inspect function is already set for OrderServiceMock.UpdateOrder")
	}

	mmUpdateOrder.mock.inspectFuncUpdateOrder = f

	return mmUpdateOrder
}

// Return sets up results that will be returned by OrderService.UpdateOrder
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) Return(err error) *OrderServiceMock {
	if mmUpdateOrder.mock.funcUpdateOrder != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Set")
	}

	if mmUpdateOrder.defaultExpectation == nil {
		mmUpdateOrder.defaultExpectation = &OrderServiceMockUpdateOrderExpectation{mock: mmUpdateOrder.mock}
	}
	mmUpdateOrder.defaultExpectation.results = &OrderServiceMockUpdateOrderResults{err}
	mmUpdateOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateOrder.mock
}

// Set uses given function f to mock the OrderService.UpdateOrder method
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) Set(f func(ctx context.Context, orderNumber string, status string, accrual int64) (err error)) *OrderServiceMock {
	if mmUpdateOrder.defaultExpectation != nil {
		mmUpdateOrder.mock.t.Fatalf("Default expectation is already set for the OrderService.UpdateOrder method")
	}

	if len(mmUpdateOrder.expectations) > 0 {
		mmUpdateOrder.mock.t.Fatalf("Some expectations are already set for the OrderService.UpdateOrder method")
	}

	mmUpdateOrder.mock.funcUpdateOrder = f
	mmUpdateOrder.mock.funcUpdateOrderOrigin = minimock.CallerInfo(1)
	return mmUpdateOrder.mock
}

// When sets expectation for the OrderService.UpdateOrder which will trigger the result defined by the following
// Then helper
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) When(ctx context.Context, orderNumber string, status string, accrual int64) *OrderServiceMockUpdateOrderExpectation {
	if mmUpdateOrder.mock.funcUpdateOrder != nil {
		mmUpdateOrder.mock.t.Fatalf("OrderServiceMock.UpdateOrder mock is already set by Set")
	}

	expectation := &OrderServiceMockUpdateOrderExpectation{
		mock:               mmUpdateOrder.mock,
		params:             &OrderServiceMockUpdateOrderParams{ctx, orderNumber, status, accrual},
		expectationOrigins: OrderServiceMockUpdateOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateOrder.expectations = append(mmUpdateOrder.expectations, expectation)
	return expectation
}

// Then sets up OrderService.UpdateOrder return parameters for the expectation previously defined by the When method
func (e *OrderServiceMockUpdateOrderExpectation) Then(err error) *OrderServiceMock {
	e.results = &OrderServiceMockUpdateOrderResults{err}
	return e.mock
}

// Times sets number of times OrderService.UpdateOrder should be invoked
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) Times(n uint64) *mOrderServiceMockUpdateOrder {
	if n == 0 {
		mmUpdateOrder.mock.t.Fatalf("Times of OrderServiceMock.UpdateOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateOrder.expectedInvocations, n)
	mmUpdateOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateOrder
}

func (mmUpdateOrder *mOrderServiceMockUpdateOrder) invocationsDone() bool {
	if len(mmUpdateOrder.expectations) == 0 && mmUpdateOrder.defaultExpectation == nil && mmUpdateOrder.mock.funcUpdateOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateOrder.mock.afterUpdateOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateOrder implements mm_worker.OrderService
func (mmUpdateOrder *OrderServiceMock) UpdateOrder(ctx context.Context, orderNumber string, status string, accrual int64) (err error) {
	mm_atomic.AddUint64(&mmUpdateOrder.beforeUpdateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateOrder.afterUpdateOrderCounter, 1)

	mmUpdateOrder.t.Helper()

	if mmUpdateOrder.inspectFuncUpdateOrder != nil {
		mmUpdateOrder.inspectFuncUpdateOrder(ctx, orderNumber, status, accrual)
	}

	mm_params := OrderServiceMockUpdateOrderParams{ctx, orderNumber, status, accrual}

	// Record call args
	mmUpdateOrder.UpdateOrderMock.mutex.Lock()
	mmUpdateOrder.UpdateOrderMock.callArgs = append(mmUpdateOrder.UpdateOrderMock.callArgs, &mm_params)
	mmUpdateOrder.UpdateOrderMock.mutex.Unlock()

	for _, e := range mmUpdateOrder.UpdateOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateOrder.UpdateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateOrder.UpdateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateOrder.UpdateOrderMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateOrder.UpdateOrderMock.defaultExpectation.paramPtrs

		mm_got := OrderServiceMockUpdateOrderParams{ctx, orderNumber, status, accrual}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateOrder.t.Errorf("OrderServiceMock.UpdateOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateOrder.UpdateOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderNumber != nil && !minimock.Equal(*mm_want_ptrs.orderNumber, mm_got.orderNumber) {
				mmUpdateOrder.t.Errorf("OrderServiceMock.UpdateOrder got unexpected parameter orderNumber, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateOrder.UpdateOrderMock.defaultExpectation.expectationOrigins.originOrderNumber, *mm_want_ptrs.orderNumber, mm_got.orderNumber, minimock.Diff(*mm_want_ptrs.orderNumber, mm_got.orderNumber))
			}

			if mm_want_ptrs.status != nil && !minimock.Equal(*mm_want_ptrs.status, mm_got.status) {
				mmUpdateOrder.t.Errorf("OrderServiceMock.UpdateOrder got unexpected parameter status, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateOrder.UpdateOrderMock.defaultExpectation.expectationOrigins.originStatus, *mm_want_ptrs.status, mm_got.status, minimock.Diff(*mm_want_ptrs.status, mm_got.status))
			}

			if mm_want_ptrs.accrual != nil && !minimock.Equal(*mm_want_ptrs.accrual, mm_got.accrual) {
				mmUpdateOrder.t.Errorf("OrderServiceMock.UpdateOrder got unexpected parameter accrual, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateOrder.UpdateOrderMock.defaultExpectation.expectationOrigins.originAccrual, *mm_want_ptrs.accrual, mm_got.accrual, minimock.Diff(*mm_want_ptrs.accrual, mm_got.accrual))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateOrder.t.Errorf("OrderServiceMock.UpdateOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateOrder.UpdateOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateOrder.UpdateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateOrder.t.Fatal("No results are set for the OrderServiceMock.UpdateOrder")
		}
		return (*mm_results).err
	}
	if mmUpdateOrder.funcUpdateOrder != nil {
		return mmUpdateOrder.funcUpdateOrder(ctx, orderNumber, status, accrual)
	}
	mmUpdateOrder.t.Fatalf("Unexpected call to OrderServiceMock.UpdateOrder. %v %v %v %v", ctx, orderNumber, status, accrual)
	return
}

// UpdateOrderAfterCounter returns a count of finished OrderServiceMock.UpdateOrder invocations
func (mmUpdateOrder *OrderServiceMock) UpdateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateOrder.afterUpdateOrderCounter)
}

// UpdateOrderBeforeCounter returns a count of OrderServiceMock.UpdateOrder invocations
func (mmUpdateOrder *OrderServiceMock) UpdateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateOrder.beforeUpdateOrderCounter)
}

// Calls returns a list of arguments used in each call to OrderServiceMock.UpdateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateOrder *mOrderServiceMockUpdateOrder) Calls() []*OrderServiceMockUpdateOrderParams {
	mmUpdateOrder.mutex.RLock()

	argCopy := make([]*OrderServiceMockUpdateOrderParams, len(mmUpdateOrder.callArgs))
	copy(argCopy, mmUpdateOrder.callArgs)

	mmUpdateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateOrderDone returns true if the count of the UpdateOrder invocations corresponds
// the number of defined expectations
func (m *OrderServiceMock) MinimockUpdateOrderDone() bool {
	if m.UpdateOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateOrderMock.invocationsDone()
}

// MinimockUpdateOrderInspect logs each unmet expectation
func (m *OrderServiceMock) MinimockUpdateOrderInspect() {
	for _, e := range m.UpdateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderServiceMock.UpdateOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateOrderCounter := mm_atomic.LoadUint64(&m.afterUpdateOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateOrderMock.defaultExpectation != nil && afterUpdateOrderCounter < 1 {
		if m.UpdateOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderServiceMock.UpdateOrder at\n%s", m.UpdateOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderServiceMock.UpdateOrder at\n%s with params: %#v", m.UpdateOrderMock.defaultExpectation.expectationOrigins.origin, *m.UpdateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateOrder != nil && afterUpdateOrderCounter < 1 {
		m.t.Errorf("Expected call to OrderServiceMock.UpdateOrder at\n%s", m.funcUpdateOrderOrigin)
	}

	if !m.UpdateOrderMock.invocationsDone() && afterUpdateOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderServiceMock.UpdateOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateOrderMock.expectedInvocations), m.UpdateOrderMock.expectedInvocationsOrigin, afterUpdateOrderCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetOrdersForCheckingStatusInspect()

			m.MinimockUpdateOrderInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetOrdersForCheckingStatusDone() &&
		m.MinimockUpdateOrderDone()
}
