// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophermart/internal/models"
)

// OrderServiceMock implements mm_getorderhandler.OrderService
type OrderServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetOrdersByUser          func(ctx context.Context, userID int64) (oa1 []models.Order, err error)
	funcGetOrdersByUserOrigin    string
	inspectFuncGetOrdersByUser   func(ctx context.Context, userID int64)
	afterGetOrdersByUserCounter  uint64
	beforeGetOrdersByUserCounter uint64
	GetOrdersByUserMock          mOrderServiceMockGetOrdersByUser
}

// NewOrderServiceMock returns a mock for mm_getorderhandler.OrderService
func NewOrderServiceMock(t minimock.Tester) *OrderServiceMock {
	m := &OrderServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetOrdersByUserMock = mOrderServiceMockGetOrdersByUser{mock: m}
	m.GetOrdersByUserMock.callArgs = []*OrderServiceMockGetOrdersByUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrderServiceMockGetOrdersByUser struct {
	optional           bool
	mock               *OrderServiceMock
	defaultExpectation *OrderServiceMockGetOrdersByUserExpectation
	expectations       []*OrderServiceMockGetOrdersByUserExpectation

	callArgs []*OrderServiceMockGetOrdersByUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderServiceMockGetOrdersByUserExpectation specifies expectation struct of the OrderService.GetOrdersByUser
type OrderServiceMockGetOrdersByUserExpectation struct {
	mock               *OrderServiceMock
	params             *OrderServiceMockGetOrdersByUserParams
	paramPtrs          *OrderServiceMockGetOrdersByUserParamPtrs
	expectationOrigins OrderServiceMockGetOrdersByUserExpectationOrigins
	results            *OrderServiceMockGetOrdersByUserResults
	returnOrigin       string
	Counter            uint64
}

// OrderServiceMockGetOrdersByUserParams contains parameters of the OrderService.GetOrdersByUser
type OrderServiceMockGetOrdersByUserParams struct {
	ctx    context.Context
	userID int64
}

// OrderServiceMockGetOrdersByUserParamPtrs contains pointers to parameters of the OrderService.GetOrdersByUser
type OrderServiceMockGetOrdersByUserParamPtrs struct {
	ctx    *context.Context
	userID *int64
}

// OrderServiceMockGetOrdersByUserResults contains results of the OrderService.GetOrdersByUser
type OrderServiceMockGetOrdersByUserResults struct {
	oa1 []models.Order
	err error
}

// OrderServiceMockGetOrdersByUserOrigins contains origins of expectations of the OrderService.GetOrdersByUser
type OrderServiceMockGetOrdersByUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) Optional() *mOrderServiceMockGetOrdersByUser {
	mmGetOrdersByUser.optional = true
	return mmGetOrdersByUser
}

// Expect sets up expected params for OrderService.GetOrdersByUser
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) Expect(ctx context.Context, userID int64) *mOrderServiceMockGetOrdersByUser {
	if mmGetOrdersByUser.mock.funcGetOrdersByUser != nil {
		mmGetOrdersByUser.mock.t.Fatalf("OrderServiceMock.GetOrdersByUser mock is already set by Set")
	}

	if mmGetOrdersByUser.defaultExpectation == nil {
		mmGetOrdersByUser.defaultExpectation = &OrderServiceMockGetOrdersByUserExpectation{}
	}

	if mmGetOrdersByUser.defaultExpectation.paramPtrs != nil {
		mmGetOrdersByUser.mock.t.Fatalf("OrderServiceMock.GetOrdersByUser mock is already set by ExpectParams functions")
	}

	mmGetOrdersByUser.defaultExpectation.params = &OrderServiceMockGetOrdersByUserParams{ctx, userID}
	mmGetOrdersByUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetOrdersByUser.expectations {
		if minimock.Equal(e.params, mmGetOrdersByUser.defaultExpectation.params) {
			mmGetOrdersByUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetOrdersByUser.defaultExpectation.params)
		}
	}

	return mmGetOrdersByUser
}

// ExpectCtxParam1 sets up expected param ctx for OrderService.GetOrdersByUser
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) ExpectCtxParam1(ctx context.Context) *mOrderServiceMockGetOrdersByUser {
	if mmGetOrdersByUser.mock.funcGetOrdersByUser != nil {
		mmGetOrdersByUser.mock.t.Fatalf("OrderServiceMock.GetOrdersByUser mock is already set by Set")
	}

	if mmGetOrdersByUser.defaultExpectation == nil {
		mmGetOrdersByUser.defaultExpectation = &OrderServiceMockGetOrdersByUserExpectation{}
	}

	if mmGetOrdersByUser.defaultExpectation.params != nil {
		mmGetOrdersByUser.mock.t.Fatalf("OrderServiceMock.GetOrdersByUser mock is already set by Expect")
	}

	if mmGetOrdersByUser.defaultExpectation.paramPtrs == nil {
		mmGetOrdersByUser.defaultExpectation.paramPtrs = &OrderServiceMockGetOrdersByUserParamPtrs{}
	}
	mmGetOrdersByUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetOrdersByUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetOrdersByUser
}

// ExpectUserIDParam2 sets up expected param userID for OrderService.GetOrdersByUser
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) ExpectUserIDParam2(userID int64) *mOrderServiceMockGetOrdersByUser {
	if mmGetOrdersByUser.mock.funcGetOrdersByUser != nil {
		mmGetOrdersByUser.mock.t.Fatalf("OrderServiceMock.GetOrdersByUser mock is already set by Set")
	}

	if mmGetOrdersByUser.defaultExpectation == nil {
		mmGetOrdersByUser.defaultExpectation = &OrderServiceMockGetOrdersByUserExpectation{}
	}

	if mmGetOrdersByUser.defaultExpectation.params != nil {
		mmGetOrdersByUser.mock.t.Fatalf("OrderServiceMock.GetOrdersByUser mock is already set by Expect")
	}

	if mmGetOrdersByUser.defaultExpectation.paramPtrs == nil {
		mmGetOrdersByUser.defaultExpectation.paramPtrs = &OrderServiceMockGetOrdersByUserParamPtrs{}
	}
	mmGetOrdersByUser.defaultExpectation.paramPtrs.userID = &userID
	mmGetOrdersByUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetOrdersByUser
}

// Inspect accepts an inspector function that has same arguments as the OrderService.GetOrdersByUser
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) Inspect(f func(ctx context.Context, userID int64)) *mOrderServiceMockGetOrdersByUser {
	if mmGetOrdersByUser.mock.inspectFuncGetOrdersByUser != nil {
		mmGetOrdersByUser.mock.t.Fatalf("Inspect function is already set for OrderServiceMock.GetOrdersByUser")
	}

	mmGetOrdersByUser.mock.inspectFuncGetOrdersByUser = f

	return mmGetOrdersByUser
}

// Return sets up results that will be returned by OrderService.GetOrdersByUser
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) Return(oa1 []models.Order, err error) *OrderServiceMock {
	if mmGetOrdersByUser.mock.funcGetOrdersByUser != nil {
		mmGetOrdersByUser.mock.t.Fatalf("OrderServiceMock.GetOrdersByUser mock is already set by Set")
	}

	if mmGetOrdersByUser.defaultExpectation == nil {
		mmGetOrdersByUser.defaultExpectation = &OrderServiceMockGetOrdersByUserExpectation{mock: mmGetOrdersByUser.mock}
	}
	mmGetOrdersByUser.defaultExpectation.results = &OrderServiceMockGetOrdersByUserResults{oa1, err}
	mmGetOrdersByUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetOrdersByUser.mock
}

// Set uses given function f to mock the OrderService.GetOrdersByUser method
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) Set(f func(ctx context.Context, userID int64) (oa1 []models.Order, err error)) *OrderServiceMock {
	if mmGetOrdersByUser.defaultExpectation != nil {
		mmGetOrdersByUser.mock.t.Fatalf("Default expectation is already set for the OrderService.GetOrdersByUser method")
	}

	if len(mmGetOrdersByUser.expectations) > 0 {
		mmGetOrdersByUser.mock.t.Fatalf("Some expectations are already set for the OrderService.GetOrdersByUser method")
	}

	mmGetOrdersByUser.mock.funcGetOrdersByUser = f
	mmGetOrdersByUser.mock.funcGetOrdersByUserOrigin = minimock.CallerInfo(1)
	return mmGetOrdersByUser.mock
}

// When sets expectation for the OrderService.GetOrdersByUser which will trigger the result defined by the following
// Then helper
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) When(ctx context.Context, userID int64) *OrderServiceMockGetOrdersByUserExpectation {
	if mmGetOrdersByUser.mock.funcGetOrdersByUser != nil {
		mmGetOrdersByUser.mock.t.Fatalf("OrderServiceMock.GetOrdersByUser mock is already set by Set")
	}

	expectation := &OrderServiceMockGetOrdersByUserExpectation{
		mock:               mmGetOrdersByUser.mock,
		params:             &OrderServiceMockGetOrdersByUserParams{ctx, userID},
		expectationOrigins: OrderServiceMockGetOrdersByUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetOrdersByUser.expectations = append(mmGetOrdersByUser.expectations, expectation)
	return expectation
}

// Then sets up OrderService.GetOrdersByUser return parameters for the expectation previously defined by the When method
func (e *OrderServiceMockGetOrdersByUserExpectation) Then(oa1 []models.Order, err error) *OrderServiceMock {
	e.results = &OrderServiceMockGetOrdersByUserResults{oa1, err}
	return e.mock
}

// Times sets number of times OrderService.GetOrdersByUser should be invoked
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) Times(n uint64) *mOrderServiceMockGetOrdersByUser {
	if n == 0 {
		mmGetOrdersByUser.mock.t.Fatalf("Times of OrderServiceMock.GetOrdersByUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetOrdersByUser.expectedInvocations, n)
	mmGetOrdersByUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetOrdersByUser
}

func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) invocationsDone() bool {
	if len(mmGetOrdersByUser.expectations) == 0 && mmGetOrdersByUser.defaultExpectation == nil && mmGetOrdersByUser.mock.funcGetOrdersByUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetOrdersByUser.mock.afterGetOrdersByUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetOrdersByUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetOrdersByUser implements mm_getorderhandler.OrderService
func (mmGetOrdersByUser *OrderServiceMock) GetOrdersByUser(ctx context.Context, userID int64) (oa1 []models.Order, err error) {
	mm_atomic.AddUint64(&mmGetOrdersByUser.beforeGetOrdersByUserCounter, 1)
	defer mm_atomic.AddUint64(&mmGetOrdersByUser.afterGetOrdersByUserCounter, 1)

	mmGetOrdersByUser.t.Helper()

	if mmGetOrdersByUser.inspectFuncGetOrdersByUser != nil {
		mmGetOrdersByUser.inspectFuncGetOrdersByUser(ctx, userID)
	}

	mm_params := OrderServiceMockGetOrdersByUserParams{ctx, userID}

	// Record call args
	mmGetOrdersByUser.GetOrdersByUserMock.mutex.Lock()
	mmGetOrdersByUser.GetOrdersByUserMock.callArgs = append(mmGetOrdersByUser.GetOrdersByUserMock.callArgs, &mm_params)
	mmGetOrdersByUser.GetOrdersByUserMock.mutex.Unlock()

	for _, e := range mmGetOrdersByUser.GetOrdersByUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.oa1, e.results.err
		}
	}

	if mmGetOrdersByUser.GetOrdersByUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetOrdersByUser.GetOrdersByUserMock.defaultExpectation.Counter, 1)
		mm_want := mmGetOrdersByUser.GetOrdersByUserMock.defaultExpectation.params
		mm_want_ptrs := mmGetOrdersByUser.GetOrdersByUserMock.defaultExpectation.paramPtrs

		mm_got := OrderServiceMockGetOrdersByUserParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetOrdersByUser.t.Errorf("OrderServiceMock.GetOrdersByUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetOrdersByUser.GetOrdersByUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetOrdersByUser.t.Errorf("OrderServiceMock.GetOrdersByUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetOrdersByUser.GetOrdersByUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetOrdersByUser.t.Errorf("OrderServiceMock.GetOrdersByUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetOrdersByUser.GetOrdersByUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetOrdersByUser.GetOrdersByUserMock.defaultExpectation.results
		if mm_results == nil {
			mmGetOrdersByUser.t.Fatal("No results are set for the OrderServiceMock.GetOrdersByUser")
		}
		return (*mm_results).oa1, (*mm_results).err
	}
	if mmGetOrdersByUser.funcGetOrdersByUser != nil {
		return mmGetOrdersByUser.funcGetOrdersByUser(ctx, userID)
	}
	mmGetOrdersByUser.t.Fatalf("Unexpected call to OrderServiceMock.GetOrdersByUser. %v %v", ctx, userID)
	return
}

// GetOrdersByUserAfterCounter returns a count of finished OrderServiceMock.GetOrdersByUser invocations
func (mmGetOrdersByUser *OrderServiceMock) GetOrdersByUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetOrdersByUser.afterGetOrdersByUserCounter)
}

// GetOrdersByUserBeforeCounter returns a count of OrderServiceMock.GetOrdersByUser invocations
func (mmGetOrdersByUser *OrderServiceMock) GetOrdersByUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetOrdersByUser.beforeGetOrdersByUserCounter)
}

// Calls returns a list of arguments used in each call to OrderServiceMock.GetOrdersByUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetOrdersByUser *mOrderServiceMockGetOrdersByUser) Calls() []*OrderServiceMockGetOrdersByUserParams {
	mmGetOrdersByUser.mutex.RLock()

	argCopy := make([]*OrderServiceMockGetOrdersByUserParams, len(mmGetOrdersByUser.callArgs))
	copy(argCopy, mmGetOrdersByUser.callArgs)

	mmGetOrdersByUser.mutex.RUnlock()

	return argCopy
}

// MinimockGetOrdersByUserDone returns true if the count of the GetOrdersByUser invocations corresponds
// the number of defined expectations
func (m *OrderServiceMock) MinimockGetOrdersByUserDone() bool {
	if m.GetOrdersByUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetOrdersByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetOrdersByUserMock.invocationsDone()
}

// MinimockGetOrdersByUserInspect logs each unmet expectation
func (m *OrderServiceMock) MinimockGetOrdersByUserInspect() {
	for _, e := range m.GetOrdersByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderServiceMock.GetOrdersByUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetOrdersByUserCounter := mm_atomic.LoadUint64(&m.afterGetOrdersByUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetOrdersByUserMock.defaultExpectation != nil && afterGetOrdersByUserCounter < 1 {
		if m.GetOrdersByUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderServiceMock.GetOrdersByUser at\n%s", m.GetOrdersByUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderServiceMock.GetOrdersByUser at\n%s with params: %#v", m.GetOrdersByUserMock.defaultExpectation.expectationOrigins.origin, *m.GetOrdersByUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetOrdersByUser != nil && afterGetOrdersByUserCounter < 1 {
		m.t.Errorf("Expected call to OrderServiceMock.GetOrdersByUser at\n%s", m.funcGetOrdersByUserOrigin)
	}

	if !m.GetOrdersByUserMock.invocationsDone() && afterGetOrdersByUserCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderServiceMock.GetOrdersByUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetOrdersByUserMock.expectedInvocations), m.GetOrdersByUserMock.expectedInvocationsOrigin, afterGetOrdersByUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetOrdersByUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetOrdersByUserDone()
}
